ezsystems/repository-forms

- bundle/Controller/TestController.php
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_definition_row.html.twig
- bundle/Resources/views/ContentType/update_content_type.html.twig
- bundle/Resources/views/FieldDefinition/ezstring_edit.html.twig
- bundle/Resources/views/update_content_type.html.twig
- composer.json
- lib/FieldType/DataTransformer/TextLineValueTransformer.php
- lib/FieldType/FieldTypeFormMapperInterface.php
- lib/FieldType/Mapper/TextLineFormMapper.php
- lib/Form/Type/ContentTypeUpdateType.php
- lib/Form/Type/FieldDefinition/FieldDefinitionType.php
- tests/RepositoryForms/FieldType/DataTransformer/TextLineValueTransformerTest.php
> https://jira.ez.no/browse/EZP-24304
Added `getFieldDefinitionEditConfig()` to FieldTypeFormMapperInterface.
Returned value is a hash which may contain:
* `template`: template where specific form fields defined in mapFieldDefinitionForm() will be displayed.
* `vars`: Hash of additional variables to pass to the template.
Provided template will be included during FieldDefinition rendering, in order to add potential additional fields.
Variables passed to the form are:
* `data`: FieldDefinitionData object
* `languageCode`: Language code as passed to the main form
* `contentTypeDraft`: The ContentTypeDraft object
* `form`: Current FieldDefinition form
Note that it is *not mandatory* to provide a template. If a FieldType doesn't need additional form fields (i.e. no validator or field …
> EZP-24304: Provide a way to customize field definition form views

- bundle/Controller/TestController.php
- bundle/Resources/config/services.yml
- bundle/Resources/config/validation.yml
- bundle/Resources/translations/validators.en.xlf
- composer.json
- lib/Data/FieldDefinitionData.php
- lib/Validator/Constraints/FieldDefinitionDefaultValue.php
- lib/Validator/Constraints/FieldDefinitionDefaultValueValidator.php
- lib/Validator/Constraints/FieldSettings.php
- lib/Validator/Constraints/FieldSettingsValidator.php
- lib/Validator/Constraints/FieldTypeValidator.php
- lib/Validator/Constraints/FieldValueValidator.php
- lib/Validator/Constraints/UniqueContentTypeIdentifier.php
- lib/Validator/Constraints/UniqueContentTypeIdentifierValidator.php
- lib/Validator/Constraints/UniqueFieldDefinitionIdentifier.php
- lib/Validator/Constraints/UniqueFieldDefinitionIdentifierValidator.php
- lib/Validator/Constraints/ValidatorConfiguration.php
- lib/Validator/Constraints/ValidatorConfigurationValidator.php
- tests/RepositoryForms/Validator/Constraints/FieldDefinitionDefaultValueTest.php
- tests/RepositoryForms/Validator/Constraints/FieldSettingsTest.php
- tests/RepositoryForms/Validator/Constraints/FieldSettingsValidatorTest.php
- tests/RepositoryForms/Validator/Constraints/UniqueContentTypeIdentifierTest.php
- tests/RepositoryForms/Validator/Constraints/UniqueContentTypeIdentifierValidatorTest.php
- tests/RepositoryForms/Validator/Constraints/UniqueFieldDefinitionIdentifierTest.php
- tests/RepositoryForms/Validator/Constraints/UniqueFieldDefinitionIdentifierValidatorTest.php
- tests/RepositoryForms/Validator/Constraints/ValidatorConfigurationTest.php
- tests/RepositoryForms/Validator/Constraints/ValidatorConfigurationValidatorTest.php
> https://jira.ez.no/browse/EZP-24309
Adds validation for ContentTypeData and FieldDefinitionData.
Follow ups:
* Add a target property/getter to `\eZ\Publish\SPI\FieldType\ValidationError` so that we can easily identify on which field validation errors occur (at field type level)
> Fix EZP-24309: Implement validation for ContentType forms

- bundle/Controller/ContentTypeController.php
- bundle/Resources/config/services.yml
- bundle/Resources/config/validation.yml
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_definition_row.html.twig
- lib/Event/RepositoryFormEvents.php
- lib/Form/Processor/ContentTypeFormProcessor.php
- lib/Form/Type/ContentTypeUpdateType.php
- lib/Form/Type/FieldDefinition/FieldDefinitionType.php
- lib/Validator/Constraints/UniqueContentTypeIdentifier.php
- lib/Validator/Constraints/UniqueContentTypeIdentifierValidator.php
- tests/RepositoryForms/Form/Processor/ContentTypeFormProcessorTest.php
- tests/RepositoryForms/Validator/Constraints/UniqueContentTypeIdentifierTest.php
- tests/RepositoryForms/Validator/Constraints/UniqueContentTypeIdentifierValidatorTest.php
> https://jira.ez.no/browse/EZP-24381
This PR simply adds the possibility to *publish* a ContentTypeDraft.
It also:
* Makes it possible to create a ContentTypeDraft out of an existing ContentType if it doesn't exist yet.
* Fixes ContentType identifier uniqueness validator to allow edition of an existing ContentType.
> Fix EZP-24381: As a RepositoryForms user, I want to be able to publish a content type draft

- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_types.html.twig
- lib/FieldType/Mapper/IntegerFormMapper.php
Manual test. Requires this change in the fieldvalue converter to work: https://github.com/ezsystems/ezpublish-kernel/pull/1264
https://jira.ez.no/browse/EZP-24397
> Fix EZP-24397: Implement FieldDefinition form mapper for ezinteger

- lib/Form/Type/ContentTypeUpdateType.php
> https://jira.ez.no/browse/EZP-24440
Depends on https://github.com/ezsystems/ezpublish-kernel/pull/1293
In addition, FieldTypes are now sorted nicely :smile:
> Fix EZP-24440: Filter FieldType selection in ContentType edition

- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_definition_row.html.twig
- bundle/Resources/views/ContentType/field_types.html.twig
- lib/FieldType/Mapper/DateTimeFormMapper.php
- lib/Form/DataTransformer/DateIntervalToArrayTransformer.php
- lib/Form/Type/DateTimeIntervalType.php
- tests/RepositoryForms/FieldType/DataTransformer/DateIntervalToArrayTransformerTest.php
Symfony forms don't support DateInterval. This adds a custom form field type.
https://jira.ez.no/browse/EZP-24390
> Fix EZP-24390: Implement FieldDefinition form mapper for ezdatetime

- composer.json
As we're gonna tag 0.1.0.
Shouldn't require changes to ezplatform, as it requires repository-forms: ~0.1@dev, meaning that it should pick the branch alias instead, right ?
> [req] Changed branch-alias to 0.2.x-dev

- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_types.html.twig
- lib/FieldType/Mapper/RelationFormMapper.php
It's unclear how the field for "Default selection item" should be set up. In legacy this lets you browse for a node, and stores a node ID: https://github.com/ezsystems/ezpublish-legacy/blob/master/design/standard/templates/class/datatype/edit/ezobjectrelation.tpl#L16
In the Type, the setting is a string, and the validator accepts strings:
https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/FieldType/Relation/Type.php#L91
However, the Converter then stores this in dataInt2, so any actual string value is lost:
https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/RelationConverter.php#L72
The doc agrees it is a string, doesn't specify how it should be used, but says it is for future use: …
> Fix EZP-24446: Implement ezrelation FieldDefinition form mapper

- lib/Data/ContentTypeData.php
- lib/Data/Mapper/ContentTypeDraftMapper.php
- lib/Data/NewnessChecker.php
- lib/Data/RoleData.php
* Changed getIdentifier() method name + visibility in NewnessChecker trait, to ensure no collision with regular public getters from value objects
* Fixed ContentTypeDraftMapper. All properties except identifier must be copied from ContentTypeDraft
when a new one is created
> Small fixes in NewnessChecker & ContentTypeDraftMapper

- lib/Form/Type/ContentTypeUpdateType.php
- lib/Form/Type/RoleUpdateType.php
> https://jira.ez.no/browse/EZP-24752
This patch deactivates validation when submitting ContentType / Role editing forms with the cancel button.
For this to completely work, a piece of JS should be implemented in PlatformUI to deactivate HTML5 validation as well.
> Fix EZP-24752: Cancel buttons should be not trigger validation in PlatformUI

- lib/Data/Mapper/RoleMapper.php
- lib/Data/RoleData.php
- lib/Form/Processor/RoleFormProcessor.php
- lib/Validator/Constraints/UniqueRoleIdentifierValidator.php
- tests/RepositoryForms/Data/Mapper/RoleMapperTest.php
Makes use of role draft features added in main PR in ezpublish-kernel.
I removed the RoleFormProcessor I had here earlier. I moved code from here to the RoleFormProcessor in PlatformUI because I needed access to the notification feature it has, and I thought repository-forms should not depend on PlatformUI. On the other hand it means role editing will only work in PlatformUI. Unsure if this is the right way.
Requirement for https://github.com/ezsystems/ezpublish-kernel/pull/1376
https://jira.ez.no/browse/EZP-24701
> Fix EZP-24701: Role versioning

- bundle/Resources/translations/validators.en.xlf
Fixed message translations to say a-z, and made them more similar.
https://jira.ez.no/browse/EZP-25026
> Fix EZP-25026: Content type identifier validation message should say latin1

- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_types.html.twig
- lib/FieldType/Mapper/SelectionFormMapper.php
This is the simplest solution, with no javascript. It adds a button "Add option / remove empty options" which will remove any empty options, and add a new one if none are empty. Will reload the form for each press of the button.
Dynamic editing via javascript is a bit more complex, see http://symfony.com/doc/current/cookbook/form/form_collections.html#cookbook-form-collections-new-prototype
https://jira.ez.no/browse/EZP-25002
> Fix EZP-25002: Unable to add more options to ezselection field type

- lib/Form/ActionDispatcher/AbstractActionDispatcher.php
- lib/Form/ActionDispatcher/ActionDispatcherInterface.php
The default form action is always dispatched first. When no action is specified (as when pressing enter in a repoform) the default action is dispatched a second time. There's no need for this, and in some forms it leads to an error (identifier already exists).
Note: The forms behave a bit differently because actions are set up differently. When pressing enter, the role and content type edit forms save and reload. The section and content type group forms save and close.
https://jira.ez.no/browse/EZP-24942
Also required: https://github.com/ezsystems/PlatformUIBundle/pull/403
> Fix EZP-24942: Press <Enter> in repository form raises a notification error

- lib/Data/ContentTypeData.php
- lib/Data/Mapper/ContentTypeDraftMapper.php
- lib/Form/Processor/ContentTypeFormProcessor.php
- tests/RepositoryForms/Data/ContentTypeDataTest.php
- tests/RepositoryForms/Data/Mapper/ContentTypeDraftMapperTest.php
- tests/RepositoryForms/Form/Processor/ContentTypeFormProcessorTest.php
> Implements https://jira.ez.no/browse/EZP-24569
> Status: Ready for review
> BDD for this: https://github.com/ezsystems/PlatformUIBundle/pull/423
Changes:
- Fielddefs are sorted when the content type is updated
- New fielddefs are created with position = max existing position + 1, so they show up last
- When the position is the same, sort by ~~create order~~ identifier (alphabetically ascending)
Tasks
> Fix EZP-24569: Automatically compute FieldDefinition position

- lib/Data/Role/PolicyDataTrait.php
- lib/Form/Processor/PolicyFormProcessor.php
- tests/RepositoryForms/Form/Processor/PolicyFormProcessorTest.php
> https://jira.ez.no/browse/EZP-25079
When saving a policy without publishing, we now retrieve the updated role and inject
the new policy into the data object.
> Fix EZP-25079: When saving a new policy draft module/function choice is lost

- bundle/Resources/config/role.yml
- bundle/Resources/translations/ezrepoforms_role.en.xlf
- lib/Limitation/Mapper/GroupLimitationMapper.php
- lib/Limitation/Mapper/LanguageLimitationMapper.php
- lib/Limitation/Mapper/MultipleSelectionBasedMapper.php
- lib/Limitation/Mapper/ObjectStateLimitationMapper.php
- lib/Limitation/Mapper/OwnerLimitationMapper.php
- lib/Limitation/Mapper/ParentDepthLimitationMapper.php
> Implements https://jira.ez.no/browse/EZP-25021
> State: Ready for review
Adds the missing limitation mappers, used when editing role policies.
**TODO**
> Fix EZP-25021: Implement missing limitation mappers

- lib/FieldType/Mapper/TextLineFormMapper.php
> Part of https://jira.ez.no/browse/EZP-25342
> Related PR https://github.com/ezsystems/ezpublish-kernel/pull/1553
Added a min attribute to the ```input type="number"``` so capable browsers can warn the user if negative value (or ```0```) is entered.
> Fix EZP-25432 In Textline fieldtype, is being permitted the "Minimum length" and "Maximum length" to have negative values

- lib/Form/Processor/RoleFormProcessor.php
- tests/RepositoryForms/Form/Processor/RoleFormProcessorTest.php
> Fixes https://jira.ez.no/browse/EZP-25203
> Also required: https://github.com/ezsystems/PlatformUIBundle/pull/465
> Status: Ready for review
Let the default action call the save role action. Let the save role action both save and publish.
> Fix EZP-25203: Pressing <Enter> when creating a role saves the role but don't publish it

- .travis.yml
Not supported by `ezpublish-kernel` anymore.
> [travis] removed php 5.4 from the matrix

- bundle/Resources/config/role.yml
- bundle/Resources/translations/ezrepoforms_role.en.xlf
- bundle/Resources/views/Limitation/udw_limitation_value.html.twig
- lib/Limitation/DataTransformer/UDWBasedValueTransformer.php
- lib/Limitation/Mapper/SubtreeLimitationMapper.php
- lib/Limitation/Mapper/UDWBasedMapper.php
> Implements https://jira.ez.no/browse/EZP-25159
> State: Ready for review
> Also requires https://github.com/ezsystems/PlatformUIBundle/pull/433
Adds the missing, UDW-based limitation mappers, used when editing role policies. Extracted from https://github.com/ezsystems/repository-forms/pull/58
> Fix EZP-25159: Implement missing limitation mappers Node and Subtree

- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezplatform_fields_groups.en.xlf
- composer.json
- lib/Form/Processor/ContentTypeFormProcessor.php
- lib/Form/Type/FieldDefinition/FieldDefinitionType.php
- tests/RepositoryForms/Form/Processor/ContentTypeFormProcessorTest.php
> Implements http://jira.ez.no/browse/EZP-25376
> Integrates fields groups added in https://github.com/ezsystems/ezpublish-kernel/pull/1575
> Requires ezpublish-kernel:6.3@dev (FieldsGroups API)
Integrates fields groups in ContentType edit forms. Backward compatibility is covered by injecting `fields_groups.list` service using a setter (avoids adding another optional argument to the ctor), and making it optional in the code.
> EZP-25376: implemented FieldsGroups in ContentType edition

- composer.json
> Re-opening of #76 against 1.1
> Fixes [EZP-25685](https://jira.ez.no/browse/EZP-25685), [EZP-25689](https://jira.ez.no/browse/EZP-25689), [EZP-25691](https://jira.ez.no/browse/EZP-25691), [EZP-25677](https://jira.ez.no/browse/EZP-25677)
Changes to PropertyAccess (https://github.com/symfony/property-access/commit/d3b7d77fb3c815e2d2d70bc6b8df7f2b6ea821f5) create a regression in multiple content type forms.
The regression is fixed in https://github.com/symfony/symfony/commit/2b30d48 on the 2.7 branch, not tagged yet.
> Fixed form errors due to symfony 2.7.11

- bundle/Controller/UserRegisterController.php
- bundle/DependencyInjection/Configuration/Parser/UserRegistration.php
- bundle/EzSystemsRepositoryFormsBundle.php
- bundle/Resources/config/ezpublish_default_settings.yml
- bundle/Resources/config/services.yml
- features/Context/UserRegistrationContext.php
- features/User/Registration/user_registration.feature
- lib/Data/Mapper/UserRegisterMapper.php
- lib/UserRegister/ConfigurableRegistrationGroupLoader.php
- lib/UserRegister/RegistrationGroupLoader.php
> Implements [EZP-25840](https://jira.ez.no/browse/EZP-25840)
Adds a `RegistrationGroupLoader`, with a `ConfigurableRegistrationGroupLoader` that receives a newly added `user.registration_group_id` siteaccess aware configuration variable. This variable is configured as follows:
```yaml
ezpublish:
system:
<scope>:
users:
registration_group_id: 11
```
> Made user registration group configurable

- bundle/Controller/UserRegisterController.php
- bundle/Resources/config/services.yml
- lib/Data/Mapper/UserRegisterMapper.php
- lib/UserRegister/ConfigurableRegistrationContentTypeLoader.php
- lib/UserRegister/ConfigurableRegistrationGroupLoader.php
- lib/UserRegister/ConfigurableSudoRepositoryLoader.php
- lib/UserRegister/RegistrationContentTypeLoader.php
> Implements [EZP-25863](https://jira.ez.no/browse/EZP-25863)
Changes the hardcoded `"eng-GB"` to the site's most prioritized language.
The `UserRegisterMapper` is now a service. It is changed to accept parameters using a `setParam` method, that accepts `"language"`. The language is read from the configuration using the expression language (see `services.yml`).
Other changes (refactoring commit):
- ContentType and Parent Group loading is now handled by dedicated loaders ( `RegistrationContentTypeLoader` and `RegistrationGroupLoader`), both used by the `UserRegisterMapper`.
> EZP-25863: Made user register use the main language

- behat_suites.yml
- bundle/Controller/UserRegisterController.php
- bundle/DependencyInjection/Configuration/Parser/UserRegistration.php
- bundle/EzSystemsRepositoryFormsBundle.php
- bundle/Resources/config/ezpublish_default_settings.yml
- bundle/Resources/config/routing.yml
- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_user_registration.en.xlf
- bundle/Resources/views/User/register_confirmation.html.twig
- features/Context/UserRegistrationContext.php
- features/User/Registration/user_registration.feature
- lib/Data/Mapper/UserRegisterMapper.php
- lib/Data/User/UserAccountFieldData.php
- lib/Data/User/UserCreateData.php
- lib/FieldType/Mapper/UserAccountFieldValueFormMapper.php
- lib/Form/Processor/UserRegisterFormProcessor.php
- lib/Form/Type/User/UserAccountType.php
- lib/Form/Type/User/UserRegisterType.php
- lib/Security/UserRegisterPolicyProvider.php
- lib/UserRegister/ConfigurableRegistrationContentTypeLoader.php
- lib/UserRegister/ConfigurableRegistrationGroupLoader.php
- lib/UserRegister/ConfigurableSudoRepositoryLoader.php
- lib/UserRegister/RegistrationContentTypeLoader.php
- lib/UserRegister/RegistrationGroupLoader.php
> Epic: [EZP-24258](https://jira.ez.no/browse/EZP-24258)
Adds real user registration support through the `/register` route. Add the `user/register` policy to the anonymous user to enable it (or use the admin account). After registering, the user is redirected to a page that confirms registration.
> Feature: user registration

- behat_suites.yml
- bundle/Controller/UserRegisterController.php
- bundle/DependencyInjection/Configuration/Parser/UserRegistration.php
- bundle/Resources/config/ezpublish_default_settings.yml
- bundle/Resources/config/services.yml
- features/Context/UserRegistrationContext.php
- features/User/Registration/user_registration.feature
- lib/EventListener/ViewTemplatesListener.php
- lib/UserRegister/View/UserRegisterConfirmView.php
- lib/UserRegister/View/UserRegisterFormView.php
> Implements [EZP-25373](https://jira.ez.no/browse/EZP-25373)
> Status: ready for review
> [Behat scenario](https://github.com/ezsystems/repository-forms/blob/ezp25373-user_registration_templates/features/User/Registration/user_registration.feature#L36-L74)
Registration form and confirmation templates can be customized using the `ezpublish.user_registration.templates` siteaccess aware settings:
```twig
ezpublish:
system:
default:
user_registration:
templates:
form: 'path/to/user/registration_form.html.twig'
confirmation: 'path/to/user/registration_confirmation.html.twig'
```
Registration group configuration is adapted to the `users` -> `user_registration` setting modification above:
```
ezpublish:
system:
default:
user_registration:
group_id: 123
```
- Changes the UserController to return …
> Make user registration templates customizable

- bundle/Controller/UserRegisterController.php
Changes the exception thrown when the user doesn't have the `user/register` policy from a basic `Exception` to `UnauthorizedHttpException`.
Benefit is that it shows a permission error and not a system one in production mode.
> Throw an UnauthorizedHttpException if not allowed to register

- lib/Validator/Constraints/FieldTypeValidator.php
- tests/RepositoryForms/Validator/Constraints/FieldSettingsValidatorTest.php
- tests/RepositoryForms/Validator/Constraints/ValidatorConfigurationValidatorTest.php
> Follow up to https://jira.ez.no/browse/EZP-26148
> Status: Ready for review
During https://github.com/ezsystems/repository-forms/pull/93 it was found that https://github.com/ezsystems/ezpublish-kernel/pull/1749 introduced a regression in repoforms. It turns out that repoforms automatically wraps field error parameters in `%`s, while kernel REST doesn't. So the fix in the kernel meant we got double-wrapped params in repoforms.
This undoes the wrapping in repoforms, while simplifying the code.
**Alternative:** Introduce automatic %-wrapping in REST. I'm not a fan, because a) KISS, and b) Symfony docs assume no automagic, let's stay in sync with that: http://symfony.com/doc/2.7/components/translation/usage.html#message-placeholders
> Fix EZP-26148: String length validation error contains %-symbols

- lib/FieldType/Mapper/CountryFormMapper.php
- lib/FieldType/Mapper/DateFormMapper.php
- lib/FieldType/Mapper/DateTimeFormMapper.php
- lib/FieldType/Mapper/MediaFormMapper.php
- lib/FieldType/Mapper/PageFormMapper.php
- lib/FieldType/Mapper/RelationListFormMapper.php
- lib/FieldType/Mapper/TimeFormMapper.php
- lib/Form/Type/ContentType/ContentTypeUpdateType.php
- lib/Form/Type/DateTimeIntervalType.php
- lib/Form/Type/Role/PolicyType.php
- lib/Limitation/Mapper/MultipleSelectionBasedMapper.php
This PR is related to [EZP-26128](https://jira.ez.no/browse/EZP-26128) and fixes deprecations related to `choices_as_values` option of `ChoiceType` form field. Required changes are described in [upgrade notes](https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md#form).
**TODO**:
*This should be a part of #93 but I've missed those warnings before, sorry for the mess.*
> EZP-26128: Fix deprecated form field ChoiceType options

- composer.json
Reasoning:
1) This would allow to test eZ Platform 1.5 with Symfony 3.x
2) `require` section is wrong anyhow, since it's missing some other dependencies, like Twig or Symfony Event Dispatcher component, for stuff available in `lib`
> Use symfony/symfony in require section

- .travis.yml
> [EZP-26728](http://jira.ez.no/browse/EZP-26728)
> EZP-26728: removed PHP 5.5 from travis matrix

- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_types.html.twig
- lib/FieldType/Mapper/RichTextFormMapper.php
> Fixes [EZP-25007](https://jira.ez.no/browse/EZP-25007)
> **IMPORTANT**: It has to be merged along with [Kernel PR #1915](https://github.com/ezsystems/ezpublish-kernel/pull/1915).
This PR removes `numRows` setting from the `RichText` Field Type and will also have its ezpublish-kernel counterpart.
**TODO**:
> EZP-25007: "Number of text rows in the editor" should be removed from RichText fieldtype

- lib/Form/Type/ContentType/ContentTypeUpdateType.php
JIRA: https://jira.ez.no/browse/EZP-25923
This patch disables the publish button (*OK*) until the Content Type has at least a field definition. While at it, I also disable the *Remove selected field definitions* button under the same condition.
manual tests
> Fix EZP-25923: Creating a content type without attributes raise a 503 Service Unavailable

- bundle/Resources/config/validation.yml
- bundle/Resources/translations/validators.en.xlf
- tests/RepositoryForms/Validator/Constraints/UniqueRoleIdentifierTest.php
- tests/RepositoryForms/Validator/Constraints/UniqueRoleIdentifierValidatorTest.php
> JIRA: https://jira.ez.no/browse/EZP-25197
This PR adds missing validation of the role form, especially:
* Uniqueness of the role name (fixed incorrect FQN of RoleData class in validation.yml)
* Not blank role name (currently there is only required attribute on `<input />` tag)
* Max length of the role name
> EZP-25197: Missing validation of the role form

- bundle/Resources/translations/ezplatform_fields_groups.en.xlf
This a follow up on https://github.com/ezsystems/ezpublish-kernel/pull/1988 
Adding translation for "Metadata" which was a missing item on default Field Group list
Related Jira issue: https://jira.ez.no/browse/EZP-26608
> EZP-26608 adding translation for "Metadata"

- .php_cs
- lib/Form/Type/ContentType/ContentTypeUpdateType.php
This is a port of https://github.com/ezsystems/repository-forms/pull/117 for `1.5` version
This fixes the https://jira.ez.no/browse/EZP-25923 for `Platform 1.7` as this version relies on `Repository-Forms` in version `1.5`
> Fix EZP-25923: disable content-type form buttons when not usable

- bundle/Resources/config/validation.yml
- bundle/Resources/translations/validators.en.xlf
- lib/Validator/Constraints/UniqueLanguageCodeValidator.php
- tests/RepositoryForms/Validator/Constraints/UniqueLanguageCodeTest.php
- tests/RepositoryForms/Validator/Constraints/UniqueLanguageCodeValidatorTest.php
> JIRA: https://jira.ez.no/browse/EZP-27370
This PR adds missing validation of the language form, especially:
* Uniqueness of the language code
* Requirement of non blank value on language code and name
* Max length of the language code and name
> EZP-27370: Missing validation of the language create/update form

- lib/FieldType/DataTransformer/FieldValueTransformer.php
- tests/RepositoryForms/FieldType/DataTransformer/FieldValueTransformerTest.php
> JIRA: https://jira.ez.no/browse/EZP-26878
This PR allow to set default value of ezinteger to 0 and also adds a missing unit tests for  `EzSystems\RepositoryForms\FieldType\DataTransformer\FieldValueTransformer`. Malfunctioning found by QA when https://github.com/ezsystems/repository-forms/pull/119 was tested.
> EZP-26878: ezinteger is not accepting value 0 as default value

- lib/Limitation/Mapper/ObjectStateLimitationMapper.php
When multiple states have the same name the group is needed to differentiate the two.
> [EZP-27435] Show state group in state option label

- features/Context/ContentType.php
- features/Context/FieldTypeFormContext.php
- features/Context/PagelayoutContext.php
- features/Context/SelectionFieldTypeFormContext.php
- features/Context/UserRegistrationContext.php
This is a follow-up on #129 changing `PHPUnit_Framework_Assert` to `PHPUnit\Framework\Assert`.
Background: found when [running tests](https://travis-ci.org/ezsystems/ezplatform/jobs/254384022#L1249) on eZ Platform `v2` which installed PHPUnit `6.x`
**TODO**:
> [PHPUnit] Replaced PHPUnit_Framework_Assert with namespaced class reference

- lib/Validator/Constraints/UniqueContentTypeIdentifierValidator.php
- tests/RepositoryForms/Validator/Constraints/UniqueContentTypeIdentifierValidatorTest.php
> JIRA: https://jira.ez.no/browse/EZP-27690
As same as https://github.com/ezsystems/repository-forms/pull/137: `UniqueContentTypeIdentifier` validator should not be executed when identifier is `null`, instead, an error should be raised by `NotBlank` validator (already configured https://github.com/ezsystems/repository-forms/blob/master/bundle/Resources/config/validation.yml#L6).
1.  Create a new content type
2. Set the identifier as a space
3. Save the content type
4.  Notification contains text
`Failed to load 'http://192.168.56.102/pjax/contenttype/update/2/eng-GB'`
instead of a regular validation error message. Error labels aren't displayed under form fields.
> Fix EZP-27690: Disable checking uniqueness of content type identifier for null

- lib/Validator/Constraints/UniqueRoleIdentifierValidator.php
- tests/RepositoryForms/Validator/Constraints/UniqueRoleIdentifierValidatorTest.php
> JIRA: https://jira.ez.no/browse/EZP-27512
`UniqueRoleIdentifier` validator should not be executed when `identifier` is `null`, instead error should be raised by `NotBlank` validator (already configured https://github.com/ezsystems/repository-forms/blob/master/bundle/Resources/config/validation.yml#L68). 
1. Create a new role
2. Set the name as a space
3. Save the role
4. Error `Failed to load 'http://.../pjax/role/update/8` instead of `Invalid form data` is displayed to user
> Fix EZP-27513: Disable checking uniqueness of role identifier for null

- bundle/Resources/views/Limitation/udw_limitation_value.html.twig
- lib/Limitation/DataTransformer/UDWBasedValueTransformer.php
> Fix https://jira.ez.no/browse/EZP-27659
> QA
Existing node/subtree limitations are not displayed when editing a policy. This ensures they are visible.
Fixes:
> EZP-27659 Subtree and Node policy limitations can't be viewed

- bundle/Resources/config/services.yml
- bundle/Resources/views/Content/content_form.html.twig
- bundle/Resources/views/Content/form_fields.html.twig
- features/Context/ContentEdit.php
- features/Context/FieldTypeFormContext.php
- features/Context/SelectionFieldTypeFormContext.php
- features/Context/UserRegistrationContext.php
- features/FieldTypeForm/checkbox_fieldtype_edit_form.feature
- features/FieldTypeForm/selection_fieldtype_edit_form.feature
- features/FieldTypeForm/textline_fieldtype_edit_form.feature
- features/FieldTypeForm/user_fieldtype_edit_form.feature
- lib/FieldType/DataTransformer/DateTimeValueTransformer.php
- lib/FieldType/DataTransformer/DateValueTransformer.php
- lib/FieldType/Mapper/CheckboxFormMapper.php
- lib/FieldType/Mapper/DateFormMapper.php
- lib/FieldType/Mapper/DateTimeFormMapper.php
- lib/FieldType/Mapper/FloatFormMapper.php
- lib/FieldType/Mapper/IntegerFormMapper.php
- lib/FieldType/Mapper/TextBlockFormMapper.php
- lib/FieldType/Mapper/TextLineFormMapper.php
- lib/FieldType/Mapper/TimeFormMapper.php
- lib/FieldType/Mapper/UrlFormMapper.php
- lib/Form/Type/FieldValue/DateTimeLocalType.php
- lib/Form/Type/FieldValue/UrlType.php
> JIRA: https://jira.ez.no/browse/EZP-26700
This PR provides basic editing support for:
* `ezstring` [EZP-27627: Implement editing support for TextLine FieldType](https://jira.ez.no/browse/EZP-27627) 
* `eztext` [EZP-27644: Implement editing support for TextBlock FieldType](https://jira.ez.no/browse/EZP-27644) 
* `ezurl` [EZP-27645: Implement editing support for Url FieldType](https://jira.ez.no/browse/EZP-27645) 
* `ezemail` [EZP-27619: Implement editing support for EmailAddress FieldType](https://jira.ez.no/browse/EZP-27619) 
* `ezdatetime` [EZP-27634: Implement editing support for DateAndTime FieldType](https://jira.ez.no/browse/EZP-27634) 
* `ezdate` [EZP-27635: Implement editing support for Date FieldType](https://jira.ez.no/browse/EZP-27635) 
* `eztime` [EZP-27636: Implement editing …
> EZP-26700: Implement editing support for more FieldTypes

- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_types.html.twig
- lib/FieldType/Mapper/AbstractRelationFormMapper.php
- lib/FieldType/Mapper/RelationFormMapper.php
- lib/FieldType/Mapper/RelationListFormMapper.php
This is related to this PR: https://github.com/ezsystems/ezpublish-kernel/pull/2022
I made a base class for the relation forms instead of duplication. I hope this is not a problem.
It adds a new translation... dunno whats the proper way for that. I updated the file by hand.
> EZP-24800 Support allowed classes limitation for object relation fields

- lib/Validator/Constraints/FieldValueValidator.php
This allows ContentTypes to have an empty value even when marked as required.
My interpretation of 'required' applies to the the ContentField not the Type.
https://jira.ez.no/browse/EZP-27793
> EZP-27793: fix updating ContentType with required value

- bundle/Resources/views/Limitation/udw_limitation_value.html.twig
> Fixes https://jira.ez.no/browse/EZP-27819
> Pending QA
When editing limitations for a policy that can have Node and Subtree limitations, but doesn't, Twig throws an exception because it is trying to render a Location with an empty string as ID.
Fixing this by verifying we have an ID to render. Thanks to @Plopix!
> EZP-27819: Template exception when editing policies with no node and subtree limitation

- bundle/Resources/views/Content/content_form.html.twig
- bundle/Resources/views/Content/form_fields.html.twig
> JIRA: https://jira.ez.no/browse/EZP-26700
This PR improves theming for content editing form. It allows to overwrite whole rows which is a ground base for some fieldtypes with specific markup i.e. `ezauthor`.
> EZP-26700: Provide better theming support to allow overwriting content editing form rows

- bundle/Resources/translations/ezrepoforms_role.en.xlf
- lib/Form/Type/Role/PolicyType.php
> JIRA: https://jira.ez.no/browse/EZP-27873
This PR adds two missing translations for the following keys: 
* `role.policy.all_modules`
* `role.policy.all_modules_all_functions`
in "Policy type" choice field in "New policy" form
> Fix EZP-27873: Added translations for role.policy.all_modules/role.policy.all_modules_all_functions

- bundle/Resources/config/services.yml
- doc/bc/changes-1.10.md
- lib/FieldType/DataTransformer/RelationListValueTransformer.php
- lib/FieldType/DataTransformer/RelationValueTransformer.php
- lib/FieldType/Mapper/AbstractRelationFormMapper.php
- lib/FieldType/Mapper/RelationFormMapper.php
- lib/FieldType/Mapper/RelationListFormMapper.php
> JIRA: https://jira.ez.no/browse/EZP-27661 and https://jira.ez.no/browse/EZP-27642
* `ezobjectrelation` [EZP-27641: Implement editing support for Relation FieldType](https://jira.ez.no/browse/EZP-27641) 
* `ezobjectrelationlist` [EZP-27642: Implement editing support for RelationList FieldType](https://jira.ez.no/browse/EZP-27642) 
Please note it isn't prepared for Content translation yet. It also requires JS enrichment done in Hybrid UI.
> Implement editing support for Relation and RelationList FieldTypes

- bundle/Resources/config/routing.yml
- doc/specifications/content_edit.md
- lib/Form/Processor/ContentFormProcessor.php
> Fix https://jira.ez.no/browse/EZP-27762
> Ready for review
Ensure our route doesn't conflict with legacy content edit, by changing `/content/edit/...` to `/content/edit/draft/...`.
Debatable: Renaming the route from `ez_content_edit` to `ez_content_draft_edit`, as I've done. The fix is smaller if we don't.
> EZP-27762 content/edit routing conflict with legacy

- bundle/Resources/config/services.yml
- doc/bc/changes-1.10.md
- lib/FieldType/DataTransformer/RichTextValueTransformer.php
- lib/FieldType/Mapper/RichTextFormMapper.php
> JIRA: https://jira.ez.no/browse/EZP-27628
* `ezrichtext` [EZP-27628: Implement editing support for RichText FieldType](https://jira.ez.no/browse/EZP-27628) 
It exposes `<textarea></textarea>` element accepting RichText's XML markup.
Please note it isn't prepared for Content translation yet. It also requires JS enrichment done in Hybrid UI.
> EZP-27628: Implement editing support for RichText FieldType

- bundle/Controller/ContentEditController.php
- bundle/Controller/UserRegisterController.php
- bundle/DependencyInjection/Configuration/Parser/ContentEdit.php
- bundle/EzSystemsRepositoryFormsBundle.php
- bundle/Resources/config/ezpublish_default_settings.yml
- bundle/Resources/config/services.yml
- doc/bc/changes-1.10.md
- lib/Content/View/ContentCreateDraftView.php
- lib/Content/View/ContentEditView.php
> JIRA: https://jira.ez.no/browse/EZP-27884
Changed return type of the controller's actions. It now returns `View` objects which are rendered by `ViewManager`. Templates are injected from parameters which can be easily configured. It uses the same principle as UserRegister.
> EZP-27884: Create extensibility point for views overriding in content edit and draft create

- .php_cs
This PR updates php-cs-fixer config to align with changes introduced by `v2.7.1`.
**Backporting this** to `1.5` as this is the oldest branch supported by `1.7 LTS`.
**TODO**:
> [CS] Aligned php-cs-fixer config with changes introduced by v2.7.1

- composer.json
#161 introduced minimal requirement on `php-cs-fixer` 2.7 but it wasn't specified in the `composer.json`. To keep things clear I added this so that developers can fix their code using bundled (`bin/php-cs-fixer`) fixer.
> Added `friendsofphp/php-cs-fixer` requirement to `composer.json`

- bin/extract-translations.sh
- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_policies.en.xlf
- lib/Translation/LimitationTranslationExtractor.php
> JIRA: https://jira.ez.no/browse/EZP-28072
This PR adds translations for limitation identifiers which are same for 1.X and 2.X versions of the administration panel.  
As has been noted by @Nattfarinn on Slack, we can't use dynamic translation keys, because JMS Translation Bundle can't extract them. This PR omits this limitation by providing custom `\JMS\TranslationBundle\Translation\ExtractorInterface` impl. for limitation identifiers. 
Translated limitation identifiers are display on view is that same way as currently: 
```twig
{{ ('policy.limitation.identifier.' ~ (limitation.identifier | lower)) | trans({}, 'ezrepoforms_policies') }}:
```
To display translated identifier of custom limitation provided in 3rd party bundle, as Developer you need create …
> EZP-28072: Translate limitation identifiers

- bundle/DependencyInjection/Configuration/Parser/LimitationValueTemplates.php
- bundle/EzSystemsRepositoryFormsBundle.php
- bundle/Resources/config/ezpublish_default_settings.yml
- bundle/Resources/config/services.yml
- lib/Limitation/Templating/LimitationBlockRenderer.php
- tests/RepositoryForms/Twig/LimitationValueRenderingExtensionTest.php
- tests/RepositoryForms/Twig/_fixtures/ez_render_limitation_value/ez_render_limitation_value.test
- tests/RepositoryForms/Twig/_fixtures/ez_render_limitation_value/templates/limitation_value_3.html.twig
> JIRA: https://jira.ez.no/browse/EZP-28077
Improvement for https://github.com/ezsystems/repository-forms/pull/159: Overriding parameters defined by 3rd party bundle is not easy for bundle developer. This PR adds an ability to configure the list of resources containing definitions of limitation value blocks, in similar to fields view/edit/definition view/definition edit blocks. Configuration example: 
```yaml
system:
default:
limitation_value_templates:
- { template: 'AppBundle:Limitation:custom_limitation_value.html.twig', priority: 0 }
```
> EZP-28077: As a bundle developer, I want to easily provide template for custom limitation value

- .travis.yml
I've noticed that Travis does not list 1.10 as active branch:
https://travis-ci.org/ezsystems/repository-forms/branches
and I think it should (and unless I'm wrong this should help?).
I've used GitHub online editor - please let me know if I should create a JIRA ticket (and have a properly named branch), I'll adjust.
> Update Travis config for 1.10 branch

- lib/FieldType/DataTransformer/DateValueTransformer.php
- lib/Form/Type/FieldType/DateFieldType.php
> JIRA: https://jira.ez.no/browse/EZP-28216
This PR changes `ezdate` form type data format to a timestamp which is easier to be handled by a JS datepicker components.
> EZP-28216: Change view format to timestamp for DateFieldType

- bundle/Controller/ContentEditController.php
- lib/Form/Processor/ContentFormProcessor.php
> JIRA: https://jira.ez.no/browse/EZP-28267
This PR adds save draft and cancel buttons to content create forms as well as changes behavior of cancel button for content create (it just redirects to parent location).
> EZP-28267: Add Save and Cancel buttons to content create page

- bundle/Controller/ContentEditController.php
- bundle/DependencyInjection/Configuration/Parser/ContentEdit.php
- bundle/Resources/config/ezpublish_default_settings.yml
- bundle/Resources/config/services.yml
- lib/Content/View/ContentCreateView.php
> JIRA: https://jira.ez.no/browse/EZP-28265
This PR brings:
* content create now returns `ContentCreateView` instead of `ContentEditView` which helps theming it separately from content draft edit action
* new configuration key `content_edit.templates.create` to assign template
> EZP-28265: Expose ContentCreateView to allow setting different theme for content creation

- lib/Form/Type/FieldType/MediaFieldType.php
> JIRA: https://jira.ez.no/browse/EZP-28278
This PR removes `required` attribute from `ezmedia` settings.
> EZP-28278: For Media field type switches seem to be always required

- lib/FieldType/DataTransformer/TimeValueTransformer.php
> JIRA: https://jira.ez.no/browse/EZP-28287
This PR fixes data transformation for `eztime` fieldtype. Previously it was using timestamps which wasn't really working - set time should be timezone independent. Right now value represents seconds which follow business logic behind `eztime`.
> EZP-28287: Inconsistent eztime value across timezones

- lib/FieldType/DataTransformer/AbstractBinaryBaseTransformer.php
- lib/FieldType/DataTransformer/BinaryFileValueTransformer.php
- lib/FieldType/DataTransformer/ImageValueTransformer.php
- lib/FieldType/DataTransformer/MediaValueTransformer.php
> JIRA: https://jira.ez.no/browse/EZP-28299
This PR fixes the problem with empty settings like width and height (in case of `ezmedia` field type). Type expects an integer for those thus it was causing an error. Data Transformers are now using default values from an empty field value.
> EZP-28299: Fixes default settings value initialization for binary based fieldtypes

- bundle/Resources/config/services.yml
- lib/Form/Processor/ContentFormProcessor.php
> JIRA: https://jira.ez.no/browse/EZP-28315
> Requires: https://github.com/ezsystems/ezpublish-kernel/pull/2163
This PR fixes the problem of deleting a draft when there is only one version in edited content. Kernel doesn't allow to remove version if that's the only one in the content. In order to fix that it's required to detect single version content and remove content completely instead. The fix relies on kernel improvement: https://github.com/ezsystems/ezpublish-kernel/pull/2163
**TODO**:
> EZP-28315: Cannot delete draft in case of nonpublished content

- bundle/Resources/translations/ezrepoforms_fieldtype.en.xlf
- lib/Form/Type/FieldType/MapLocationFieldType.php
> JIRA: https://jira.ez.no/browse/EZP-28342
MapLocation's children types had invalid input type (text instead of number) which made validation fail and also it was incorrect from HTML5 standpoint as text input should not have `min` and `max` attributes.
> EZP-28342: Invalid input type for latitude and logitude in MapLocation fieldtype

- bundle/Controller/ContentEditController.php
- bundle/Resources/config/services.yml
- lib/Data/Content/ContentUpdateData.php
- lib/FieldType/Mapper/AuthorFormMapper.php
- lib/FieldType/Mapper/BinaryFileFormMapper.php
- lib/FieldType/Mapper/CheckboxFormMapper.php
- lib/FieldType/Mapper/CountryFormMapper.php
- lib/FieldType/Mapper/DateFormMapper.php
- lib/FieldType/Mapper/DateTimeFormMapper.php
- lib/FieldType/Mapper/FloatFormMapper.php
- lib/FieldType/Mapper/FormTypeBasedFieldValueFormMapper.php
- lib/FieldType/Mapper/ISBNFormMapper.php
- lib/FieldType/Mapper/ImageFormMapper.php
- lib/FieldType/Mapper/IntegerFormMapper.php
- lib/FieldType/Mapper/KeywordFormMapper.php
- lib/FieldType/Mapper/MapLocationFormMapper.php
- lib/FieldType/Mapper/MediaFormMapper.php
- lib/FieldType/Mapper/RelationFormMapper.php
- lib/FieldType/Mapper/RelationListFormMapper.php
- lib/FieldType/Mapper/RichTextFormMapper.php
- lib/FieldType/Mapper/SelectionFormMapper.php
- lib/FieldType/Mapper/TextBlockFormMapper.php
- lib/FieldType/Mapper/TextLineFormMapper.php
- lib/FieldType/Mapper/TimeFormMapper.php
- lib/FieldType/Mapper/UrlFormMapper.php
- lib/FieldType/Mapper/UserAccountFieldValueFormMapper.php
- lib/Form/Processor/ContentFormProcessor.php
- lib/Form/Type/Content/ContentEditType.php
- lib/Form/Type/Content/ContentFieldType.php
- lib/Form/Type/FieldType/MapLocationFieldType.php
> JIRA: https://jira.ez.no/browse/EZP-27539
Translation support was never implemented in repository-forms. Now there is a need for that in new AdminUI. This PR makes fieldtypes "language" aware which is helpful for developers theming content edit page. It also fixes the issue of nontranslated labels of fieldtypes as this feature is there but never implemented in Admin UI or Platform UI.
> EZP-27539: Translation support in content edit

- lib/Form/Processor/ContentTypeFormProcessor.php
> JIRA: https://jira.ez.no/browse/EZP-28226
This PR fixes Content Type Edit > Add Field Definition action which had been failing if first field definitions were removed. It was caused by assigning already existing identifier. I created a method which resolves new name making sure it doesn't exist in edited Content Type.
It has to be ported upwards to 1.10 and master.
> EZP-28226: User can't add more fields after removing several of them

- tests/RepositoryForms/Form/Processor/ContentTypeFormProcessorTest.php
> JIRA: https://jira.ez.no/browse/EZP-28527
Test were broken by #187, this PR fixes failing test. This PR has to be merged up to the `master`.
> EZP-28527: Fix `ContentTypeFormProcessorTest::testAddFieldDefinition` test

- lib/Form/Type/FieldType/MapLocationFieldType.php
> JIRA: https://jira.ez.no/browse/EZP-28443
Address field should always be optional as ezgmaplocation only cares about latitude and longitude.
> EZP-28443: There is no validation for Address in map location

- lib/FieldType/DataTransformer/SingleSelectionValueTransformer.php
> JIRA: https://jira.ez.no/browse/EZP-28575
`SingleSelectionTransformer` was returning incompatible value (array instead of a string). This was causing an "array to string" conversion error.
> EZP-28575: User can't edit content item with ezselection

- bundle/Resources/config/role.yml
- lib/Limitation/Mapper/ContentTypeLimitationMapper.php
- lib/Limitation/Mapper/LanguageLimitationMapper.php
- lib/Limitation/Mapper/ObjectStateLimitationMapper.php
- lib/Limitation/Mapper/SectionLimitationMapper.php
- tests/RepositoryForms/Limitation/Mapper/ContentTypeLimitationMapperTest.php
- tests/RepositoryForms/Limitation/Mapper/LanguageTypeLimitationMapperTest.php
- tests/RepositoryForms/Limitation/Mapper/ObjectStateLimitationMapperTest.php
- tests/RepositoryForms/Limitation/Mapper/SectionLimitationMapperTest.php
> JIRA: https://jira.ez.no/browse/EZP-28544
This PR adds `\eZ\Publish\API\Repository\Exceptions\NotFoundException` handling in limitation value mappers, which are the cause of problem described in JIRA ticket.
> 1. Create a new eZ Platform installation.
> 2. Create a new Content Type.
> 3. Create a new Role.
> 4. Create a new Content/Read Policy in the Role created in the previous step. Add Content Type created in the second step as Limitations->Class for this Policy.
> 5. Remove Content Type created in the second step.
> 6. Try to navigate to the Role created in the third step (in the Platform UI: "Admin Panel"->"Roles"->Name of the Role).
> 7. Confirm the error described above.
> EZP-28544: Added NotFoundException handling in limitation value mappers

- composer.json
- tests/RepositoryForms/FieldType/DataTransformer/SingleSelectionValueTransformerTest.php
> JIRA: https://jira.ez.no/browse/EZP-28595
Fixes test broken by #197 and bumps package versions for `ezsystems/ezpublish-kernel` and `symfony/symfony`.
> EZP-28595: Fix SingleSelectionValueTransformer tests

- lib/Data/Mapper/UserRegisterMapper.php
- lib/Form/EventSubscriber/UserFieldsSubscriber.php
> JIRA: https://jira.ez.no/browse/EZP-28703
This PR fixes registration issue which was caused by passing `null` as a value for `UserCreateStruct::$enabled`. This was the result of assigning the value from `User/Value::$enabled` which is in fact `null` for empty fieldtype. My fix is either taking value coming from the fieldtype (in case of user create/edit) or from the `UserCreateStruct::$enabled` in registration. Also I've used `true` as a default value to reflect the behavior used in v1.
> EZP-28703: Error 400 after trying to register new user

- bundle/Controller/ContentEditController.php
- bundle/Resources/config/routing.yml
- lib/Form/ActionDispatcher/ContentDispatcher.php
- lib/Form/Processor/ContentFormProcessor.php
> JIRA: https://jira.ez.no/browse/EZP-28850
> Requires: https://github.com/ezsystems/ezplatform-admin-ui/pull/374
Right now it's not possible to return to the proper location in AdminUI as repository-forms is not passing any information about the location draft was edited from. It's also crucial for Page Builder. 
The parameter is optional and should not introduce any BC breaks.
I'm not sure how are you supposed to test it, the best thing that comes to my mind is to just test content edit in Admin UI as this is directly affected.
> EZP-28850: Add optional location parameter to draft edit for more appropriate redirection

- bundle/Controller/ContentEditController.php
- bundle/DependencyInjection/Compiler/ViewBuilderRegistryPass.php
- bundle/DependencyInjection/Configuration/Parser/ContentEditView.php
- bundle/EzSystemsRepositoryFormsBundle.php
- bundle/Resources/config/ezpublish_default_settings.yml
- bundle/Resources/config/routing.yml
- bundle/Resources/config/services.yml
- bundle/Resources/config/views.yml
- lib/Content/View/Builder/ContentEditViewBuilder.php
- lib/Content/View/ContentEditView.php
- lib/Content/View/Filter/ContentEditViewFilter.php
- lib/Content/View/Provider/Configured.php
> JIRA: https://jira.ez.no/browse/EZP-28849
> Requires: https://github.com/ezsystems/ezplatform-admin-ui/pull/375 (to work with AdminUI)
I heard from @bdunogier it was always the initial idea but no one had time to finish it. As Page Builder is meant to replace edit interface for Landing Pages we need this feature. This PR only affects draft edit action, next one will be dedicated to content create.
I'd like a solid code review as this PR might potentially introduce some BC breaks.
Might be hard to test by QA as this is mostly related to developer experience but I'd advise to get through content editing briefly. If the content editing screen is displayed correctly and the actions are performed as expected it should be alright.
> EZP-28849: Allow repository forms to use View Manager for handling draft edit controller and template dispatching

- lib/Form/Type/FieldType/BinaryBaseFieldType.php
> JIRA: https://jira.ez.no/browse/EZP-28871
The `upload_max_filesize` setting from `php.ini` should be taken into account in the validation of uploaded files, as an upper limit of upload size. 
1. Configure `upload_max_filesize` to e.g 5M
1. Create new Media -> File
2. Select large binary file larger then `upload_max_filesize`
3. Try to save content. The application will return "Internal server error" because of  `Argument 'localFile' is invalid: file does not exist or is unreadable: /var/www/...` exception
> EZP-28871: upload_max_filesize setting should be taken into account in the validation of uploaded files

- bundle/Controller/ContentEditController.php
- bundle/DependencyInjection/Compiler/ViewBuilderRegistryPass.php
- bundle/DependencyInjection/Configuration/Parser/ContentCreateView.php
- bundle/DependencyInjection/Configuration/Parser/ContentEdit.php
- bundle/EzSystemsRepositoryFormsBundle.php
- bundle/Resources/config/ezpublish_default_settings.yml
- bundle/Resources/config/routing.yml
- bundle/Resources/config/services.yml
- bundle/Resources/config/views.yml
- lib/Content/View/Builder/ContentCreateViewBuilder.php
- lib/Content/View/ContentCreateView.php
- lib/Content/View/ContentTypeValueView.php
- lib/Content/View/Filter/ContentCreateViewFilter.php
- lib/Content/View/Provider/ContentCreateView/Configured.php
- lib/Content/View/Provider/ContentEditView/Configured.php
- lib/EventListener/UserEditListener.php
> JIRA: https://jira.ez.no/browse/EZP-28861
> Requires: #215
> Requires: https://github.com/ezsystems/ezplatform-admin-ui/pull/376 (to test in AdminUI)
> EZP-28861: Allow template and controller dispatching based on matcher configuration for Content Create

- lib/Form/Type/FieldType/BinaryBaseFieldType.php
> JIRA: https://jira.ez.no/browse/EZP-28871
`\EzSystems\RepositoryForms\Form\Type\FieldType\BinaryBaseFieldType::getMaxUploadSize` is called multipe times, so it return value should be cached.
> EZP-28871: Return value of BinaryBaseFieldType::getMaxUploadSize should be cached

- lib/Form/Type/ContentType/FieldTypeChoiceType.php
Field types are currently sorted by their respectable identifiers (e.g. ezstring, eztext, etc.)
This works fine with the default build in field types but degrades UX once custom field types are introduced.
> EZP-28949: switched sort of field type selection to use human readable name

- bundle/Controller/ContentEditController.php
- bundle/Resources/views/http/302_empty_content.html.twig
- lib/Content/View/Builder/ContentCreateViewBuilder.php
- lib/Content/View/Builder/ContentEditViewBuilder.php
- lib/Content/View/ContentCreateSuccessView.php
- lib/Content/View/ContentEditSuccessView.php
> JIRA: https://jira.ez.no/browse/EZP-28944
Not the solution I'd like to have but I couldn't find any better way to solve the issue. You are expected to return `View` object from the builder where currently we are handling forms. It's not possible to return `RedirectResponse` directly which is the outcome from the `FormProcessors`. I had to hack it a little to encapsulate Response inside `ContentEditSuccessView` and `ContentCreateSuccessView` which is later picked up by `ViewTemplateListener` which is properly handling the Response. Benefit to this resolution is that you can catch the view and render the template if needed.
If anyone has better idea please let me know.
Test create and edit functionalities.
> EZP-28944: ISE 500 when deleting Draft

- bundle/Resources/views/ContentType/field_types.html.twig
Reverts ezsystems/repository-forms#219. 
That PR was causing some labels to appear twice because first it was rendering `form_row` and later `form_label`, `form_errors` and `form_widget`. 
I've moved field definition templates: https://github.com/ezsystems/ezplatform-admin-ui/pull/400 to prevent people from making AdminUI related changes in this repository.
> Revert "EZP-28930: Labels are one line below checkbox/radiobutton"

- bundle/Resources/translations/validators.en.xlf
- lib/Validator/Constraints/FieldValueValidator.php
- lib/Validator/Constraints/FieldValueValidatorMessages.php
Jira: https://jira.ez.no/browse/EZP-28902
Depends on: ezsystems/ezpublish-kernel#2279
This PR tries to handle with a new login validation error message from the kernel.
> EZP-28902: Creating a user with existing username results in Internal Server Error.

- lib/Content/View/Builder/ContentEditViewBuilder.php
- lib/Content/View/ContentEditView.php
- lib/Form/ActionDispatcher/ContentDispatcher.php
- lib/Form/Processor/ContentFormProcessor.php
> JIRA: https://jira.ez.no/browse/EZP-28939
This PR fixes the issue with unpublished drafts. It was relying on `Location` a lot but unpublished content has no location until published. My PR introduces another property to the `ContentEditView` which tells about `ParentLocation`, it allows `ContentEditView::$location` to be `null`.
> EZP-28939: Internal Server Error when saving unpublished Draft

- lib/Data/Mapper/ContentUpdateMapper.php
> JIRA: https://jira.ez.no/browse/EZP-29012
This PR fixes setting `initialLanguageCode` property on edited drafts. This allows to properly display translation language in AdminUI.
> EZP-29012: Invalid initial language code set after saving content draft

- lib/Form/Processor/ContentTypeFormProcessor.php
Done as part of https://jira.ez.no/browse/EZP-28224
This is a follow-up to https://github.com/ezsystems/repository-forms/pull/190, where the tests weren't passing on PHP5.6 (and probably a bug fix to https://github.com/ezsystems/repository-forms/pull/187)
Function `array_column` works on objects only since PHP7 [(Ref),](http://www.php.net/manual/en/function.array-column.php) `$contentTypeDraft->getFieldDefinitions()` returns an array of `FieldDefinition` objects. Changing it to `array_map` should do the trick.
> EZP-28224: Use PHP5.6 compatible function

- .travis.yml
- features/Context/PagelayoutContext.php
- features/Context/UserRegistrationContext.php
- features/User/Registration/user_registration.feature
JIRA: https://jira.ez.no/browse/EZP-28224
Three things had to be changed in order to make the tests pass:
1. Enabling Debug mode - the tests are searching for strings like 
```
```
in the page source, which AFAIK are only displayed when Debug is enabled.
2. Changing the way these strings are searched for: recently the format changed a bit (https://github.com/ezsystems/ezpublish-kernel/pull/2285), I've switched to Regex to account for that.
3. Permissions: tests were trying to create a directory in `app/Resources`, but by default the www-data is owner of the `app/config` and `src` (https://github.com/ezsystems/ezplatform/blob/1.7/bin/.travis/trusty/setup_from_external_repo.sh#L68). I've switched the tests so that they are creating it in `src/AppBundle` now.
> EZP-28224: Fix Behat tests

- composer.json
- features/Context/ContentEdit.php
- features/Context/FieldTypeFormContext.php
- features/Context/UserRegistrationContext.php
- features/FieldTypeForm/checkbox_fieldtype_edit_form.feature
- features/FieldTypeForm/selection_fieldtype_edit_form.feature
- features/FieldTypeForm/textline_fieldtype_edit_form.feature
- features/FieldTypeForm/user_fieldtype_edit_form.feature
- features/User/Registration/user_registration.feature
| **JIRA issue**     | [EZP-28224](https://jira.ez.no/browse/EZP-28224)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | master
| **BC breaks**      | no
| **Tests pass**     | 1 failure - see description for details
**Description**
Things done:
1) User fieldType has a different selector than other fields, tests are not taking it into account
2) The `has-error` class is no longer used when validating fields
3) Previously the tests were checking whether all the fields are set as required when fieldType is set as required. It had to be changed, because required User field does not have the "Enabled" field as required (allowing the user to change it). Added a way to …
> EZP-28224: Fix Behat in 2.0

- bundle/EzSystemsRepositoryFormsBundle.php
- lib/Security/UserRegisterPolicyProvider.php
Jira: https://jira.ez.no/browse/EZP-29024
Now policy `user/register` is a part of kernel. We do not need add this in the repository forms.
> EZP-29024: Adding policy user/register to the role throws 500

- bundle/Resources/config/services.yml
> [EZP-29409](https://jira.ez.no/browse/EZP-29409)
The `MaxUploadSize` class was wired as a dependency of `BinaryBaseFieldType` while it wasn't named after its type. It generated a warning:
```
Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "ezrepoforms.config_resolver.max_upload_size" service to "EzSystems\RepositoryForms\ConfigResolver\MaxUploadSize" instead.
```
This fixes it by making the FQN the service name, and aliasing the previous name to it.
> Symfony 4.x: aliased service to avoid autowiring notice

- lib/Form/Type/FieldType/AuthorFieldType.php
| **JIRA issue**     | [EZP-29318](https://jira.ez.no/browse/EZP-29318)
| **Bug/Improvement**| yes
| **Target version** | 2.1
| **BC breaks**      | no
| **Tests pass**     | yes
Author FieldType is prefilled with the data of the currently logged user (name, e-mail), to be consistent with 5.4 and v1. As a followup, I'll create PR's which will enable an editor to decide whether this FieldType should be prefilled by default at the creation Content Type level. Implementation goes to `repository-forms` as fetching current user data based on repository in `ezpublish-kernel` is quite problematic. Ref: https://github.com/ezsystems/ezpublish-kernel/pull/2392
**TODO**:
> EZP-29138: Author FieldType isn't prefilled with logged user data

- bundle/Resources/translations/ezrepoforms_fieldtype.en.xlf
- lib/FieldType/DataTransformer/ImageAssetValueTransformer.php
- lib/Form/Type/FieldType/ImageAssetFieldType.php
> JIRA: https://jira.ez.no/browse/EZP-29508
> Depends on: https://github.com/ezsystems/ezpublish-kernel/pull/2451
Impl. possibility to define Alternative Text for Image Asset.
> EZP-29508: As an editor I want to manage ALT field with an image asset field type

- bundle/Resources/config/services.yml
- lib/Form/Processor/ContentFormProcessor.php
- lib/Form/Processor/SystemUrlRedirectProcessor.php
> JIRA: https://jira.ez.no/browse/EZP-29448
> Part of : https://github.com/ezsystems/ezplatform-admin-ui/pull/641
This PR changes the redirect flow on side of repository-forms. Instead of systemURL redirect is done to `_ezpublishLocation` (so basically, how it was before `2.2`).
> EZP-29617: No route found after adding new translation

- composer.json
This is required to run Behat tests on 2.3 and not on master.
> [Composer] [Travis] Use 2.3 branch in metarepo

- lib/Content/View/Filter/ContentCreateViewFilter.php
| **JIRA issue**     | [EZP-29518](https://jira.ez.no/browse/EZP-29518)
| **Bug**| yes
| **New feature**    | no
| **Target version** | `2.3+`
| **BC breaks**      | no
| **Tests pass**     | yes
This is the required modification for https://github.com/ezsystems/ezpublish-kernel/pull/2428 to have full effect in v2.
> EZP-29518: ContentType option "Default field for sorting children" has no effect on new created objects

- lib/Form/Type/Role/LimitationType.php
- lib/Limitation/Mapper/MultipleSelectionBasedMapper.php
- lib/Limitation/Mapper/UDWBasedMapper.php
- lib/Translation/LimitationTranslationExtractor.php
| Tickets       | https://jira.ez.no/browse/EZP-29748
| Bug fix?      | no
| New feature?  | yes
See [https://github.com/ezsystems/ezplatform-admin-ui/pull/701](https://github.com/ezsystems/ezplatform-admin-ui/pull/701) [https://github.com/ezsystems/ezplatform/pull/336](https://github.com/ezsystems/ezplatform/pull/336)
> EZP-29748: Replacing the outdated verbiage of eZ Publish from eZ Platform when adding a Policy

- lib/Behat/Context/ContentTypeContext.php
JIRA: https://jira.ez.no/browse/EZP-29612
Required by https://github.com/ezsystems/developer-documentation/pull/467/files
This extends the current ContentType Context so that:
1) it's possible to remove FieldType from contentType
2) it's possible to create a Content Type with multiple fields
> Extend Content Type Context

- features/Context/ContentEdit.php
Follow-up to https://github.com/ezsystems/ezpublish-kernel/pull/2498
Which makes the tests passing again.
> Fix spelling mistake in tests

- composer.json
Checking if installing kernel with @dev helps with failing unit tests:
https://travis-ci.org/ezsystems/repository-forms/builds/467887329
AdminUI, which also runs Unit Tests, has kernel set that way already (https://github.com/ezsystems/ezplatform-admin-ui/blob/master/composer.json#L19).
> Install ezpublish-kernel with @dev

- tests/RepositoryForms/Twig/LimitationValueRenderingExtensionTest.php
> JIRA: -
Added missing `$deprecation` parameter to `\EzSystems\RepositoryForms\Tests\Twig\LimitationValueRenderingExtensionTest::doIntegrationTest`  to make this method compatible with `\eZ\Publish\Core\MVC\Symfony\Templating\Tests\Twig\Extension\FileSystemTwigIntegrationTestCase::doIntegrationTest`. 
Right now PHP is complaining about that when running unit tests locally:
```
PHP Warning:  Declaration of EzSystems\RepositoryForms\Tests\Twig\LimitationValueRenderingExtensionTest::doIntegrationTest($file, $message, $condition, $templates, $exception, $outputs) should be compatible with eZ\Publish\Core\MVC\Symfony\Templating\Tests\Twig\Extension\FileSystemTwigIntegrationTestCase::doIntegrationTest($file, $message, $condition, $templates, $exception, $outputs, $deprecation = '') in …
```
> Fixed declaration of LimitationValueRenderingExtensionTest::doIntegrationTest

- features/Context/ContentType.php
Similar as in https://github.com/ezsystems/BehatBundle/pull/73 - the dot cannot be used in Content Type identifier.
> Remove dot from Content Type identifier

- lib/Limitation/DataTransformer/UDWBasedValueModelTransformer.php
- lib/Limitation/DataTransformer/UDWBasedValueTransformer.php
- lib/Limitation/DataTransformer/UDWBasedValueViewTransformer.php
- lib/Limitation/Mapper/UDWBasedMapper.php
- tests/RepositoryForms/Limitation/DataTransformer/UDWBasedValueModelTransformerTest.php
- tests/RepositoryForms/Limitation/DataTransformer/UDWBasedValueViewTransformerTest.php
> JIRA: https://jira.ez.no/browse/EZP-29849
Changes required to make Location object available during rendering edit form of the location based limitations.  
In the limitation template (e.g. `src/bundle/Resources/views/Limitation/udw_limitation_value.html.twig` in `ezplatform-admin-ui`) location instances are available using `form.limitationValues.vars.data`. The model/view format of data is not changed:
> EZP-29849: Allow user to remove location in subtree limitation

- lib/FieldType/Mapper/AbstractRelationFormMapper.php
- lib/FieldType/Mapper/RelationFormMapper.php
- lib/FieldType/Mapper/RelationListFormMapper.php
- lib/Form/Type/FieldType/RelationFieldType.php
- lib/Form/Type/FieldType/RelationListFieldType.php
> JIRA: https://jira.ez.no/browse/EZP-30181
Follow up for https://github.com/ezsystems/repository-forms/pull/279. Editor is not able to select any content item as value of the `ezobjectrelation`/`ezobjectrelationlist` field if the starting location is not accessible for some reason (location was trashed or because of lack of permission). In such case we will fallback starting location to null witch is technically content tree root. 
In such case we assume that content tree root should be used as starting point for selection.
> EZP-30181: Editor is not able to select any item in the ezobjectrelation/ezobjectrelationlist FTs if starting location is not accessible

- lib/Content/View/Builder/ContentCreateViewBuilder.php
- lib/Content/View/Builder/ContentEditViewBuilder.php
- lib/Content/View/ContentCreateSuccessView.php
- lib/Content/View/ContentEditSuccessView.php
JIRA: https://jira.ez.no/browse/EZP-29979
> EZP-29979: As a developer I would like to use getLocation method on ContentCreateSuccessView and ContentEditSuccessView

- lib/Data/ContentTranslationData.php
- lib/FieldType/Mapper/UserAccountFieldValueFormMapper.php
- lib/Form/Type/Content/ContentEditType.php
| Tickets       | [EZP-30297](https://jira.ez.no/browse/EZP-30297)
| New feature?  |no
| Doc needed?   |no
[https://github.com/ezsystems/ezplatform-admin-ui/pull/901](https://github.com/ezsystems/ezplatform-admin-ui/pull/901)
> EZP-30297: Error when I try to add a translation for a user object

- lib/Behat/Context/UserRegistrationContext.php
After https://github.com/ezsystems/ezpublish-kernel/pull/2570 the repository-forms tests started failing with:
```
Scenario: Registration is disabled for users who do not have the "user/register" policy # vendor/ezsystems/repository-forms/features/User/Registration/user_registration.feature:6
Given I do not have the user/register policy                                          # EzSystems\RepositoryForms\Behat\Context\UserRegistrationContext::loginAsUserWithoutRegisterPolicy()
eZ\Publish\Core\Base\Exceptions\UserPasswordValidationException: Argument 'password' is invalid: Password doesn't match the following rules: User password must be at least 10 characters long, User password must include at least one upper case letter, User password must include at least one number in …
```
> Make default password pass requirements

- lib/Translation/LimitationTranslationExtractor.php
- tests/RepositoryForms/Translation/LimitationTranslationExtractorTest.php
- tests/RepositoryForms/Translation/fixtures/input_policies.yaml
| Question | Answer
| --- | ---
| **Bug** | yes
| **Target version** | `2.3` and up
There are [some policies which don't have any limitation defined](https://github.com/ezsystems/ezpublish-kernel/blob/v7.3.5/eZ/Publish/Core/settings/policies.yml#L17-L21), which results in `ez_policy_limitation` translation extractor crashing when trying to generate translations for new limitations.
Steps to reproduce: 
1. Clone eZ Platform meta repository.
2. Execute:
```bash
./bin/console translation:extract --enable-extractor=ez_policy_limitation --domain=ezrepoforms_policies --output-format=xlf --output-dir=./vendor/ezsystems/repository-forms/bundle/Resources/translations/  --dir=./vendor/ezsystems/repository-forms/bundle
```
3. Observe the following error:
```bash
In LimitationTranslationExtractor.php …
```
> Fixed ez_policy_limitation translation extractor for no limitations case

- lib/Validator/Constraints/Password.php
- tests/RepositoryForms/Validator/Constraints/PasswordTest.php
- tests/RepositoryForms/Validator/Constraints/UserAccountPasswordTest.php
> JIRA: https://jira.ez.no/browse/EZP-30417
> Depends on: https://github.com/ezsystems/ezplatform-user/pull/30
This PR allows the `Password` Constraint to be used in Annotation Assertions.
> EZP-30417: Add notifications to the password reset view

- lib/Behat/Context/ContentTypeContext.php
- lib/Behat/Context/UserRegistrationContext.php
Missing PR for https://jira.ez.no/browse/EZP-30539 , adjusting tests for the lack of PlatformBehatBundle.
This is not the cleanest of fixes, as I've missed this during https://jira.ez.no/browse/EZP-30539 - I don't think we should spend more time on this, given that repository-forms will be removed in 3.0 and the Contexts here will have to be ported and aligned to current approach in BehatBundle (some parts of that already happened).
> EZP-30539: Move Platform Behat Bundle to BehatBundle #83

- bundle/DependencyInjection/Compiler/FieldTypeFormMapperDispatcherPass.php
- bundle/Resources/config/fieldtypes.yaml
- tests/RepositoryFormsBundle/DependencyInjection/Compiler/FieldTypeFormMapperDispatcherPassTest.php
Jira: https://jira.ez.no/browse/EZP-30462
Tags used to register Field Type features in the dependency injection container should be consistent and follow Symfony convention (snake case)
Relates to:
[https://github.com/ezsystems/ezpublish-kernel/pull/2653](https://github.com/ezsystems/ezpublish-kernel/pull/2653)
[https://github.com/ezsystems/ezplatform-matrix-fieldtype/pull/15](https://github.com/ezsystems/ezplatform-matrix-fieldtype/pull/15)
```
ez.fieldFormMapper.value => ezplatform.field_type.form_mapper.value
ez.fieldFormMapper.definition => ezplatform.field_type.form_mapper.definition
```
> EZP-30462: Change `ez.fieldFormMapper` tag to `ezplatform.field_type.form_mapper`

- lib/FieldType/DataTransformer/TimeValueTransformer.php
- tests/RepositoryForms/FieldType/DataTransformer/TimeValueTransformerTest.php
**JIRA**: https://jira.ez.no/browse/EZP-30712
Can't set a time to be midnight without this fix
> EZP-30712: Fixed reverseTransform for midnight value

- bundle/Resources/views/limitation_values.html.twig
> JIRA: https://jira.ez.no/browse/EZP-30814
Continuation of https://github.com/ezsystems/ezpublish-kernel/pull/2708: replaced `spaceless` tag usages in favour of `spaceless` filter
> EZP-30814: Removed Twig deprecations

- lib/Data/Mapper/ContentTypeDraftMapper.php
- lib/Form/ActionDispatcher/AbstractActionDispatcher.php
- tests/RepositoryForms/Data/Mapper/ContentTypeDraftMapperTest.php
> JIRA: https://jira.ez.no/browse/EZP-30812
Fixed the following deprecation message:
```
Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as first argument is deprecated since Symfony 4.3, pass it second and provide the event object first instead.
```
by swapping argument order in  `Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()` method calls.
> EZP-30812: Fixed deprecated use of Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch method

- tests/RepositoryForms/Twig/_fixtures/field_edit_rendering_functions/ez_render_field_definition_edit.test
> JIRA: -
Twig function  `ez_render_fielddefinition_edit` has been renamed to `ez_render_field_definition_edit`.  
Discovered during the  https://travis-ci.org/ezsystems/repository-forms/jobs/568837487 build. This is not the root cause of the issue but it needs to be fixed as well.
> Fixed broken integration test for ez_render_field_definition_edit function

- lib/Event/FieldDefinitionMappingEvent.php
> JIRA: https://jira.ez.no/browse/EZP-30828
Replaced `\Symfony\Component\EventDispatcher\Event` usage in favor of `Symfony\Contracts\EventDispatcher\Event`.
> EZP-30828: Replaced \Symfony\Component\EventDispatcher\Event usage in favor of Symfony\Contracts\EventDispatcher\Event

- lib/Behat/Context/PagelayoutContext.php
In SF4 the templates path changes from `app/Resources/views/` to `templates/`(https://github.com/symfony/symfony/blob/master/UPGRADE-4.0.md)
Adjusting tests for that. Issue detected in https://travis-ci.com/ezsystems/ezplatform-page-builder/jobs/224288223
> Adjusted tests for changes in templates path

- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
> JIRA: https://jira.ez.no/browse/EZP-30998
Current text: `Days before passwords expire:`. Expected text: `Days before password expires`
> EZP-30988: Fixed typo in the user password expiration label

- lib/FieldType/Mapper/AuthorFormMapper.php
- lib/FieldType/Mapper/CountryFormMapper.php
- lib/FieldType/Mapper/DateFormMapper.php
- lib/FieldType/Mapper/DateTimeFormMapper.php
- lib/FieldType/Mapper/MediaFormMapper.php
- lib/FieldType/Mapper/PageFormMapper.php
- lib/FieldType/Mapper/RelationFormMapper.php
- lib/FieldType/Mapper/RelationListFormMapper.php
- lib/FieldType/Mapper/TimeFormMapper.php
- lib/Form/Type/ContentType/FieldTypeChoiceType.php
- lib/Form/Type/ContentType/SortFieldChoiceType.php
- lib/Form/Type/ContentType/SortOrderChoiceType.php
- lib/Form/Type/FieldDefinition/FieldDefinitionType.php
- lib/Form/Type/FieldType/CountryFieldType.php
- lib/Form/Type/FieldType/SelectionFieldType.php
- lib/Form/Type/Role/PolicyType.php
- lib/Form/Type/URL/URLListType.php
- lib/Limitation/Mapper/MultipleSelectionBasedMapper.php
| Question          | Answer
| -------------------- | ------------------
| **JIRA issue**  | [EZP-30985](https://jira.ez.no/browse/EZP-30985)
| **Target version** | eZ Platform `2.5.x`
The `choices_as_values` Symfony form option has been deprecated since Symfony 3.1.
Ref: https://symfony.com/doc/3.4/reference/forms/types/choice.html#choices-as-values
* Author,
* Country,
* Date,
* DateTime,
* Media (Image, BinaryFile).
* Adding Field Type,
* Updating Field Type,
* Choosing sort Field Type,
* Choosing sort order,
* Setting Field Group,
* Country FT: default values,
* Selection FT: default values,
* Roles: adding/updating of policies,
* Policies: Limitations chosen from a list (Language, ContentType, etc.)
* Link manager: status filtering.
> EZP-30985: Removed deprecated choices_as_values Symfony form option

- lib/Form/Type/FieldType/RelationFieldType.php
- lib/Form/Type/FieldType/RelationListFieldType.php
| Tickets       | https://jira.ez.no/browse/EZP-30918
| New feature?  |no
| Needs?    | https://github.com/ezsystems/ezplatform-admin-ui/pull/1135
| Doc needed?   |no
This PR introduces new Relation View to display content's relations. When a user has no access to see restricted relation then proper information will be displayed. 
Related PR: https://github.com/ezsystems/ezplatform-admin-ui/pull/1135
Location view:
Edit view:
> EZP-30918: Added information to relations about restricted access

- bundle/DependencyInjection/Compiler/FieldTypeFormMapperDispatcherPass.php
- bundle/DependencyInjection/Compiler/LimitationFormMapperPass.php
- bundle/DependencyInjection/Compiler/LimitationValueMapperPass.php
- lib/Behat/Context/ContentTypeContext.php
- lib/Behat/Context/PagelayoutContext.php
- lib/Behat/Context/SelectionFieldTypeFormContext.php
- lib/ConfigResolver/ConfigurableSudoRepositoryLoader.php
- lib/Content/View/Builder/ContentCreateViewBuilder.php
- lib/Content/View/Builder/ContentEditViewBuilder.php
- lib/FieldType/DataTransformer/AbstractBinaryBaseTransformer.php
- lib/FieldType/DataTransformer/DateTimeValueTransformer.php
- lib/FieldType/DataTransformer/DateValueTransformer.php
- lib/FieldType/DataTransformer/ImageAssetValueTransformer.php
- lib/FieldType/DataTransformer/TimeValueTransformer.php
- lib/Form/DataTransformer/DateIntervalToArrayTransformer.php
- lib/Form/Processor/ContentFormProcessor.php
- lib/Form/Processor/ContentTypeFormProcessor.php
- lib/Limitation/Mapper/ContentTypeLimitationMapper.php
- lib/Limitation/Mapper/LanguageLimitationMapper.php
- lib/Limitation/Mapper/ObjectStateLimitationMapper.php
- lib/Limitation/Mapper/SectionLimitationMapper.php
- lib/Limitation/Templating/LimitationBlockRenderer.php
- lib/User/ConfigurableSudoRepositoryLoader.php
- tests/RepositoryForms/Limitation/Mapper/ContentTypeLimitationMapperTest.php
- tests/RepositoryForms/Limitation/Mapper/LanguageTypeLimitationMapperTest.php
- tests/RepositoryForms/Limitation/Mapper/ObjectStateLimitationMapperTest.php
- tests/RepositoryForms/Limitation/Mapper/SectionLimitationMapperTest.php
[EZP-31021](https://jira.ez.no/browse/EZP-31021)
Main PR: https://github.com/ezsystems/ezpublish-kernel/pull/2878
> EZP-31021: Revised exception and command messages

- lib/Form/Type/FieldType/ImageFieldType.php
Jira: https://jira.ez.no/browse/EZP-31238
According the `eZ/Publish/Core/FieldType/Image/Type.php:121` (https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/FieldType/Image/Type.php#L114) the alternative text is optinal.
Creating images without an alternative texts works fine using the repository services or the backend drag&drop image creation. Creating the image through the default content edit requires the alternative text is filled. The reasons for that is that the field is not marked as optional inside the form building: `EzSystems\RepositoryForms\Form\Type\FieldType\ImageFieldType:40`.
Already approved, discussed it in Slack:
> sylvainguittard:us:  1 day ago
Hi @daavidkllr!
Sorry for the late reply. I totally agree with you, it’s inconsistent and we should fix …
> EZP-31238: marked alternative image text as optional to ensure consistence with fieldtype

- lib/Form/Type/FieldType/FloatFieldType.php
jira: https://jira.ez.no/browse/EZP-28900
The root of the issue is that our `FloatFieldType` uses view transformer : `NumberToLocalizedStringTransformer`. This transformer is not set explicitly but it is inherited from symfony's `NumberType`. Symfony NumberType needs this transformer because  default `form_fields.html.twig` use `<input type='text">`  to display `number_widget`. AdminUI overwrites symfony's `form_fields.html.twig` including `number_widget` and number are displayed as `<input type="number"`. So this transformer is no needed and causes problems described in the ticket.  
related to : https://github.com/ezsystems/ezpublish-kernel/pull/2849
> EZP-28900: Removed view transformer from FloatFieldType

- lib/Content/View/Builder/ContentEditViewBuilder.php
| Tickets       | https://jira.ez.no/browse/EZP-31310
| New feature?  |no
| Tests pass?   | yes/no
| Doc needed?   | yes/no
| Related to | <ul><li>https://github.com/ezsystems/ezplatform-admin-ui/pull/1237 </li><li>https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/269</li></ul>
When the user wants to edit the content that has multiple locations and occurs checking if unpublished draft exists then we need to know in which location the user tries to do this. This is needed to prepare proper links to edit versions. We should do this when it is possible (when a user is on the location view). When …
> EZP-31310: Fixed editing for content with multiple locations

- bundle/Controller/UserController.php
| Tickets       | [EZEE-2930](https://jira.ez.no/browse/EZEE-2930)
Another PR:
https://github.com/ezsystems/ezplatform-admin-ui/pull/1244
> EZEE-2930: Added Language obj. instance to User create/edit views

- lib/Form/Type/FieldType/UserAccountFieldType.php
This is a backport of fix introduced here:
https://github.com/ezsystems/ezplatform-content-forms/pull/17/
> EZP-31013: Use readonly instead of disabled for username form

- .travis.yml
Target version: **2.5**
While Behat Scenarios are executed inside a Docker container which relies on `$PHP_IMAGE` for Docker PHP image, the dependencies are installed relying on `$PHP_IMAGE_DEV`. For PHP 7.1 it should be set to `ezsystems/php:7.1-v1-dev`.
**TODO**
> [Travis] Set Docker PHP image used for installing dependencies

- bundle/Controller/UserController.php
- bundle/Resources/config/services.yml
|     |     |
| --- | --- |
| **JIRA issue** | [EZP-31317](https://jira.ez.no/browse/EZP-31317) |
| **Type** | Bug
| **Target version** | 2.5
User Content create & edit actions need to load Content Type in current user's preferred language so Field Definition names used to display labels in create & edit forms are displayed in a proper language.
For full description and steps to reproduce please refer to [EZP-31317](https://jira.ez.no/browse/EZP-31317).
Merge up: since in eZ Platform 3.0 we use SA-aware layer, I expect this issue does not exist there, but we need to check that (not sure if SA-aware layer has user preferred language set).
**TODO**:
> EZP-31317: Loaded ContentType using preferred language in UserController

- .travis.yml
Seems like for `master` there was an intent to run a CS job, but the script actually didn't do anything except installing dependencies. Moved `install` and `script` to proper job, so it's more readable.
:exclamation: The PR includes a merge-up of #336 and #335 , so needs to be merged fast-forward once Travis is passing.
#335 changes were automatically dropped as they were moved elsewhere I guess.
**TODO**:
> [Travis] Fixed code style check

- lib/Form/DataTransformer/TranslatablePropertyTransformer.php
- tests/RepositoryForms/Form/DataTransformer/TranslatablePropertyTransformerTest.php
| **JIRA issue**     | [EZP-31449](https://jira.ez.no/browse/EZP-31449)
| **Bug**| yes
| **New feature**    | no
| **BC breaks**      |no
| **Tests pass**     | yes
Reverse transformation in `TranslatablePropertyTransformer` was adapted to properly handle `ContentType` and `ContentType's`  fieldtype translatable fields when the empty value was provided in form.
Original kernel PR and discussion: https://github.com/ezsystems/ezpublish-kernel/pull/2988 -> closed right now.
**TODO**:
> EZP-31449: Adapted TranslatablePropertyTransformer to properly handle nulls

- bundle/Resources/translations/validators.en.xlf
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EZP-31581](https://jira.ez.no/browse/EZP-31581)
| **Type**                                   | bug
| **BC breaks**                          | no
| **Tests pass**                          | yes
| **Doc needed**                       | no
> EZP-31581: Added missing translation

- lib/FieldType/DataTransformer/DateValueTransformer.php
| Tickets       | https://jira.ez.no/browse/EZP-31557
The offset should be added to the final timestamp to convert it to the GMT time. Right now the server could be located in `America\Chicago` and the end-user with local time in Asia which in some conditions would show discrepancies in shown date. The final date during the publishing is converted to GMT time either way.
Related `admin-ui` PR: https://github.com/ezsystems/ezplatform-admin-ui/pull/1350
> EZP-31557: Added timezone offset to ezdate field form value
