- bundle/Resources/config/services.yml
- bundle/Resources/views/ContentType/field_types.html.twig
- lib/FieldType/Mapper/TextBlockFormMapper.php
Fieldsetting in place, no testing yet.
https://jira.ez.no/browse/EZP-24344
> Fix EZP-24344: Implement FieldDefinition form mapper for eztext

- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_types.html.twig
- lib/FieldType/Mapper/FloatFormMapper.php
Manual testing.
https://jira.ez.no/browse/EZP-24396
> Fix EZP-24396: Implement FieldDefinition form mapper for ezfloat

- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_definition_row.html.twig
- lib/Event/RepositoryFormEvents.php
- lib/Form/Processor/ContentTypeFormProcessor.php
- lib/Form/Type/ContentTypeUpdateType.php
- lib/Form/Type/FieldDefinition/FieldDefinitionType.php
- tests/RepositoryForms/Form/Processor/ContentTypeFormProcessorTest.php
> https://jira.ez.no/browse/EZP-24382
Based on #14
> Fix EZP-24382: As a RepositoryForms user I want to delete a FieldDefinition from a ContentType

- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_types.html.twig
- lib/FieldType/Mapper/ISBNFormMapper.php
Manual testing.
https://jira.ez.no/browse/EZP-24398
> Fix EZP-24398: Implement FieldDefinition form mapper for ezisbn

- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_types.html.twig
- lib/FieldType/DataTransformer/CountryValueTransformer.php
- lib/FieldType/Mapper/CountryFormMapper.php
- tests/RepositoryForms/FieldType/DataTransformer/CountryValueTransformerTest.php
https://jira.ez.no/browse/EZP-24389
> Fix EZP-24389: Implement FieldDefinition form mapper for ezcountry

- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_types.html.twig
- lib/FieldType/Mapper/TimeFormMapper.php
Manual testing. This is based on ezdatetime, but thankfully the tricky bits of that are not needed here, so it's pretty simple.
https://jira.ez.no/browse/EZP-24394
> Fix EZP-24394: Implement FieldDefinition form mapper for eztime

- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_types.html.twig
- lib/FieldType/Mapper/DateFormMapper.php
Manual testing. This is based on eztime, but is even simpler.
https://jira.ez.no/browse/EZP-24393
> Fix EZP-24393: Implement FieldDefinition form mapper for ezdate

- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_types.html.twig
- lib/FieldType/Mapper/BinaryFileFormMapper.php
Manual tests.
Depends on changes in Type and Converter, see: https://github.com/ezsystems/ezpublish-kernel/pull/1283
https://jira.ez.no/browse/EZP-24441
> Fix EZP-24441: Implement FieldDefinition form mapper for ezbinaryfile

- lib/FieldType/Mapper/BinaryFileFormMapper.php
Max size should be an optional setting. Follow-up to https://jira.ez.no/browse/EZP-24441
Review ping @lolautruche
> Follow-up to EZP-24441: Implement FieldDefinition form mapper for ezbinaryfile

- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_types.html.twig
- lib/FieldType/Mapper/MediaFormMapper.php
Manual tests. Similar to ezbinaryfile and ezimage, but no change to the Type needed.
https://jira.ez.no/browse/EZP-24443
> Fix EZP-24443: Implement FieldDefinition form mapper for ezmedia

- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_types.html.twig
- lib/FieldType/Mapper/PageFormMapper.php
Uses PageService to read available layouts, to populate select dropdown.
Depends on https://github.com/ezsystems/ezpublish-kernel/pull/1289
https://jira.ez.no/browse/EZP-24444
> Fix EZP-24444: Implement FieldDefinition form mapper for ezpage

- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- lib/Event/RepositoryFormEvents.php
- lib/Form/Processor/ContentTypeFormProcessor.php
- lib/Form/Type/ContentTypeUpdateType.php
- tests/RepositoryForms/Form/Processor/ContentTypeFormProcessorTest.php
> https://jira.ez.no/browse/EZP-24452
Pretty straight forward...
> Fix EZP-24452: Add cancel button in ContentType edition form

- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_definition_row.html.twig
- bundle/Resources/views/ContentType/field_types.html.twig
- lib/FieldType/Mapper/SelectionFormMapper.php
Manual test. Using the `collection` field type: http://symfony.com/doc/current/reference/forms/types/collection.html
https://jira.ez.no/browse/EZP-24448
> Fix EZP-24448: Implement FieldDefinition form mapper for ezselection

- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_types.html.twig
- lib/FieldType/Mapper/RichTextFormMapper.php
Manual testing.
Also: Tag preset field setting removed in kernel: https://github.com/ezsystems/ezpublish-kernel/pull/1301
https://jira.ez.no/browse/EZP-24449
> Fix EZP-24449: Implement FieldDefinition form mapper for RichText

- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_types.html.twig
- lib/FieldType/Mapper/ImageFormMapper.php
Manual testing. Is about the same as for ezbinaryfile.
Depends on https://github.com/ezsystems/ezpublish-kernel/pull/1291
https://jira.ez.no/browse/EZP-24442
> Fix EZP-24442: Implement FieldDefinition form mapper for ezimage

- bundle/Resources/config/kernel.yml
- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_types.html.twig
- bundle/Resources/views/content_name/content_name.html.twig
- lib/FieldType/Mapper/RelationListFormMapper.php
Manual tests.
This is based on the Relation PR: https://github.com/ezsystems/repository-forms/pull/31
UDW button used in the same way.
https://jira.ez.no/browse/EZP-24447
> Fix EZP-24447: Implement ezrelationlist FieldDefinition form mapper

- bundle/Resources/views/ContentType/field_types.html.twig
Added check for empty value. D'oh!
https://jira.ez.no/browse/EZP-24577
> Fix EZP-24577: Cannot add new relation/relationlist field types to content type

- bundle/Resources/config/services.yml
- lib/Data/Mapper/RoleMapper.php
- lib/Data/RoleData.php
- lib/Event/RepositoryFormEvents.php
- lib/Form/ActionDispatcher/RoleDispatcher.php
- lib/Form/Type/RoleUpdateType.php
Repoforms mapper for role editing, required by Role UI https://github.com/ezsystems/PlatformUIBundle/pull/294
https://jira.ez.no/browse/EZP-24685
> Fix EZP-24685: Role UI (list, view, CRUD)

- bundle/Resources/views/ContentType/field_definition_row.html.twig
- bundle/Resources/views/ContentType/field_types.html.twig
https://jira.ez.no/browse/EZP-24727
Ready for review
> EZP-24727: Add possibility to inject class for div groups

- bundle/Resources/config/section.yml
- bundle/Resources/config/services.yml
- bundle/Resources/config/validation.yml
- bundle/Resources/translations/ezrepoforms_section.en.xlf
- bundle/Resources/translations/validators.en.xlf
- lib/Data/ContentTypeData.php
- lib/Data/Mapper/SectionMapper.php
- lib/Data/NewsnessCheckable.php
- lib/Data/RoleData.php
- lib/Data/Section/SectionCreateData.php
- lib/Data/Section/SectionDataTrait.php
- lib/Data/Section/SectionUpdateData.php
- lib/Data/SectionData.php
- lib/Event/RepositoryFormEvents.php
- lib/Form/ActionDispatcher/SectionDispatcher.php
- lib/Form/Processor/SectionFormProcessor.php
- lib/Form/Type/Section/SectionDeleteType.php
- lib/Form/Type/Section/SectionType.php
- lib/Form/Type/SectionType.php
- lib/Validator/Constraints/UniqueSectionIdentifier.php
- lib/Validator/Constraints/UniqueSectionIdentifierValidator.php
- tests/RepositoryForms/Data/Mapper/SectionMapperTest.php
- tests/RepositoryForms/Form/Processor/SectionFormProcessorTest.php
> https://jira.ez.no/browse/EZP-24380
Part of https://github.com/ezsystems/PlatformUIBundle/pull/288
> Fix EZP-24380: Move section form management from PlatformUI to RepositoryForms

- bundle/Resources/config/services.yml
- bundle/Resources/config/validation.yml
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- lib/Data/ContentTypeGroup/ContentTypeGroupCreateData.php
- lib/Data/ContentTypeGroup/ContentTypeGroupDataTrait.php
- lib/Data/ContentTypeGroup/ContentTypeGroupUpdateData.php
- lib/Data/Mapper/ContentTypeGroupMapper.php
- lib/Event/RepositoryFormEvents.php
- lib/Form/ActionDispatcher/ContentTypeGroupDispatcher.php
- lib/Form/Processor/ContentTypeGroupFormProcessor.php
- lib/Form/Type/ContentType/ContentTypeGroupDeleteType.php
- lib/Form/Type/ContentType/ContentTypeGroupType.php
- tests/RepositoryForms/Data/Mapper/ContentTypeGroupMapperTest.php
- tests/RepositoryForms/Form/Processor/ContentTypeGroupFormProcessorTest.php
> https://jira.ez.no/browse/EZP-24454
Depends on https://github.com/ezsystems/ezpublish-kernel/pull/1408
> Fix EZP-24454: ContentType group CRUD

- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- lib/Form/Type/ContentType/ContentTypeDeleteType.php
> https://jira.ez.no/browse/EZP-24453
Added form type for ContentType deletion.
> Fix EZP-24453: Implement ContentType removal

- bundle/Resources/config/role.yml
- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_role.en.xlf
- lib/Data/Mapper/PolicyMapper.php
- lib/Data/Mapper/RoleMapper.php
- lib/Data/Role/PolicyCreateData.php
- lib/Data/Role/PolicyDataTrait.php
- lib/Data/Role/PolicyUpdateData.php
- lib/Data/Role/RoleData.php
- lib/Event/RepositoryFormEvents.php
- lib/Form/ActionDispatcher/PolicyDispatcher.php
- lib/Form/Processor/PolicyFormProcessor.php
- lib/Form/Processor/RoleFormProcessor.php
- lib/Form/Type/Role/PolicyDeleteType.php
- lib/Form/Type/Role/PolicyType.php
- lib/Form/Type/Role/RoleUpdateType.php
- lib/Validator/Constraints/UniqueRoleIdentifierValidator.php
- tests/RepositoryForms/Data/Mapper/PolicyMapperTest.php
- tests/RepositoryForms/Data/Mapper/RoleMapperTest.php
- tests/RepositoryForms/Form/Processor/PolicyFormProcessorTest.php
> https://jira.ez.no/browse/EZP-24711
> EZP-24711: Role policy editing step 1 & 2

- bundle/Resources/translations/ezrepoforms_role.en.xlf
- lib/Form/Type/Role/RoleAssignmentDeleteType.php
Adds role assignment delete form. Required by https://github.com/ezsystems/PlatformUIBundle/pull/344
https://jira.ez.no/browse/EZP-24700
> Fix EZP-24700: Role assignment CRUD

- bundle/DependencyInjection/Compiler/LimitationFormMapperPass.php
- bundle/EzSystemsRepositoryFormsBundle.php
- bundle/Resources/config/role.yml
- bundle/Resources/translations/ezrepoforms_role.en.xlf
- bundle/Resources/views/Limitation/base_limitation_values.html.twig
- bundle/Resources/views/Limitation/null_limitation_values.html.twig
- lib/Data/Mapper/PolicyMapper.php
- lib/Data/Role/PolicyCreateData.php
- lib/Data/Role/PolicyDataTrait.php
- lib/Data/Role/PolicyUpdateData.php
- lib/Form/Processor/PolicyFormProcessor.php
- lib/Form/Type/Role/LimitationType.php
- lib/Form/Type/Role/PolicyType.php
- lib/Limitation/LimitationFormMapperInterface.php
- lib/Limitation/LimitationFormMapperRegistry.php
- lib/Limitation/LimitationFormMapperRegistryInterface.php
- lib/Limitation/Mapper/ContentTypeLimitationMapper.php
- lib/Limitation/Mapper/MultipleSelectionBasedMapper.php
- lib/Limitation/Mapper/NullLimitationMapper.php
- lib/Limitation/Mapper/SectionLimitationMapper.php
- lib/Limitation/Mapper/SiteAccessLimitationMapper.php
- lib/Limitation/SiteAccessLimitationMapper.php
- tests/RepositoryForms/Data/Mapper/PolicyMapperTest.php
- tests/RepositoryForms/Form/Processor/PolicyFormProcessorTest.php
> https://jira.ez.no/browse/EZP-24713
Works on the same principe as FieldDefinitions. Each limitation type needs a form mapper.
Base implementation includes a mapper for SiteAccessLimitationType
> Fix EZP-24713: Policy limitations edition

- bundle/Resources/config/language.yml
- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_language.en.xlf
- lib/Data/Language/LanguageCreateData.php
- lib/Data/Language/LanguageDataTrait.php
- lib/Data/Language/LanguageUpdateData.php
- lib/Data/Mapper/LanguageMapper.php
- lib/Event/RepositoryFormEvents.php
- lib/Form/ActionDispatcher/LanguageDispatcher.php
- lib/Form/Processor/LanguageFormProcessor.php
- lib/Form/Type/Language/LanguageDeleteType.php
- lib/Form/Type/Language/LanguageType.php
- lib/Validator/Constraints/UniqueLanguageCode.php
- lib/Validator/Constraints/UniqueLanguageCodeValidator.php
- lib/Validator/Constraints/UniqueSectionIdentifierValidator.php
- tests/RepositoryForms/Data/Mapper/LanguageMapperTest.php
- tests/RepositoryForms/Form/Processor/LanguageFormProcessorTest.php
- tests/RepositoryForms/Form/Processor/SectionFormProcessorTest.php
- tests/bootstrap.php
https://jira.ez.no/browse/EZP-22658
> EZP-22658: Add Repo form support for Languages

- .travis.yml
- bin/.travis/prepare_behat.sh
- lib/Twig/FieldEditRenderingExtension.php
> JIRA: http://jira.ez.no/browse/EZP-25704
See https://github.com/ezsystems/ezpublish-kernel/pull/1637 for a description.
> EZP-25704: removed deprecated twig initRuntime() usage

- .travis.yml
- bin/.travis/prepare_behat.sh
- lib/FieldType/Mapper/TextBlockFormMapper.php
> Fixes [EZP-25750](https://jira.ez.no/browse/EZP-25750)
A wrong parameter was passed to the FieldType service thing. Also changed the form widget type that is used to textarea instead of text.
Not much to say, it just fixes it :-)
> Fix EZP-25750: textblock content edit error

- .travis.yml
- bin/.travis/prepare_behat.sh
- lib/FieldType/Mapper/TextBlockFormMapper.php
> Merge of https://github.com/ezsystems/repository-forms/pull/77 to 1.2
> [CI] merge of EZP-25750 into 1.2 (eztext error)

- behat_suites.yml
- bundle/Controller/ContentEditController.php
- bundle/Resources/config/services.yml
- bundle/Resources/views/Content/content_edit.html.twig
- features/ContentEdit/create_without_draft.feature
- features/Context/ContentEdit.php
- features/Context/PagelayoutContext.php
Title pretty much says it all. Ensures that UGC forms are well integrated in the site.
> Added pagelayout to content_edit template/controller

- bundle/Resources/translations/fr/ezrepoforms_content_type.fr.xlf
- bundle/Resources/translations/fr/ezrepoforms_language.fr.xlf
- bundle/Resources/translations/fr/ezrepoforms_role.fr.xlf
- bundle/Resources/translations/fr/ezrepoforms_section.fr.xlf
- bundle/Resources/translations/fr/validators.fr.xlf
Hello ! 
I just translated the language files in French and organized them in a fr sub-directory in the translations one.
I hope this helps.
Regards
> added French Translations

- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_content.en.xlf
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/translations/ezrepoforms_language.en.xlf
- bundle/Resources/translations/ezrepoforms_role.en.xlf
- bundle/Resources/translations/ezrepoforms_section.en.xlf
- bundle/Resources/translations/ezrepoforms_user_registration.en.xlf
- bundle/Resources/translations/validators.en.xlf
- composer.json
- lib/FieldType/Mapper/BinaryFileFormMapper.php
- lib/FieldType/Mapper/CheckboxFormMapper.php
- lib/FieldType/Mapper/CountryFormMapper.php
- lib/FieldType/Mapper/DateFormMapper.php
- lib/FieldType/Mapper/DateTimeFormMapper.php
- lib/FieldType/Mapper/FloatFormMapper.php
- lib/FieldType/Mapper/ISBNFormMapper.php
- lib/FieldType/Mapper/ImageFormMapper.php
- lib/FieldType/Mapper/IntegerFormMapper.php
- lib/FieldType/Mapper/MediaFormMapper.php
- lib/FieldType/Mapper/PageFormMapper.php
- lib/FieldType/Mapper/RelationFormMapper.php
- lib/FieldType/Mapper/RelationListFormMapper.php
- lib/FieldType/Mapper/RichTextFormMapper.php
- lib/FieldType/Mapper/SelectionFormMapper.php
- lib/FieldType/Mapper/TextBlockFormMapper.php
- lib/FieldType/Mapper/TextLineFormMapper.php
- lib/FieldType/Mapper/TimeFormMapper.php
- lib/FieldType/Mapper/UserAccountFieldValueFormMapper.php
- lib/Form/Type/ContentType/ContentTypeUpdateType.php
- lib/Translation/SortingTranslationExtractor.php
> EZP-26704
- Custom extractor for fieldtypes names
- Forced domains in mapper classes for extraction
- Regenerated strings
> JMS translation bundle integration

- bin/.travis/prepare_behat.sh
- composer.json
See https://github.com/ezsystems/PlatformUIBundle/pull/755
> Make sure to checkout the correct ezplatform branch to run behat tests

- bin/extract-translations.sh
- bundle/Resources/translations/ezplatform_fields_groups.en.xlf
- bundle/Resources/translations/ezrepoforms_content.en.xlf
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/translations/ezrepoforms_language.en.xlf
- bundle/Resources/translations/ezrepoforms_role.en.xlf
- bundle/Resources/translations/ezrepoforms_section.en.xlf
- bundle/Resources/translations/ezrepoforms_user_registration.en.xlf
- bundle/Resources/translations/validators.en.xlf
Jira : https://jira.ez.no/browse/EZP-26835
Add script to extract translation + clean jms reference file elements
This PR aloso contains the cleaned files
> EZP-26835 : Script to extract translations + update translation files

- bin/extract-translations.sh
- bundle/Resources/translations/ezrepoforms_content.en.xlf
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/translations/ezrepoforms_language.en.xlf
- bundle/Resources/translations/ezrepoforms_role.en.xlf
- bundle/Resources/translations/ezrepoforms_section.en.xlf
- bundle/Resources/translations/ezrepoforms_user_registration.en.xlf
Jira: https://jira.ez.no/browse/EZP-26835
Simplify sed command to clean file reference + make path relative
> EZP-26835 : Fix file reference in extract translations + update files

- .php_cs
- features/Context/ContentType.php
- lib/FieldType/Mapper/UserAccountFieldValueFormMapper.php
- lib/Limitation/LimitationFormMapperRegistry.php
- lib/UserRegister/ConfigurableRegistrationContentTypeLoader.php
- lib/UserRegister/ConfigurableRegistrationGroupLoader.php
- tests/RepositoryForms/FieldType/DataTransformer/MultiSelectionValueTransformerTest.php
> Make ezrobot happy again with .php_cs

- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_types.html.twig
- lib/FieldType/Mapper/SelectionFormMapper.php
JIRA: https://jira.ez.no/browse/EZP-25002
See https://github.com/ezsystems/PlatformUIBundle/pull/739
> EZP-25002: Reorganize the selection field def options markup

- .php_cs
- features/Context/ContentType.php
- lib/FieldType/Mapper/UserAccountFieldValueFormMapper.php
- lib/Form/Processor/RoleFormProcessor.php
- lib/Limitation/LimitationFormMapperRegistry.php
- lib/UserRegister/ConfigurableRegistrationContentTypeLoader.php
- lib/UserRegister/ConfigurableRegistrationGroupLoader.php
- tests/RepositoryForms/FieldType/DataTransformer/MultiSelectionValueTransformerTest.php
- tests/RepositoryForms/Twig/FieldEditRenderingExtensionTest.php
This PR is follow up on https://github.com/ezsystems/repository-forms/pull/120 
It just makes `php-cs-fixer` work again and fixes issues discovered by it
> Fix cs fixer issues

- README.md
Now release badge displays proper release number.
> Use Github to display release

- bundle/Controller/ContentEditController.php
- bundle/Resources/config/routing.yml
- bundle/Resources/views/Content/content_create_draft.html.twig
- doc/specifications/content_edit.md
- features/Context/ContentType.php
- features/Context/FieldTypeFormContext.php
- features/Context/PagelayoutContext.php
- features/Context/SelectionFieldTypeFormContext.php
- features/Context/UserRegistrationContext.php
- lib/Data/Content/ContentUpdateData.php
- lib/Data/Content/CreateContentDraftData.php
- lib/Data/Mapper/ContentUpdateMapper.php
- lib/Event/RepositoryFormEvents.php
- lib/Form/Processor/ContentFormProcessor.php
- lib/Form/Type/Content/ContentDraftCreateType.php
- lib/Validator/Constraints/FieldValueValidator.php
> Implement https://jira.ez.no/browse/EZP-27492
> Ready for review
> Based on https://github.com/ezsystems/repository-forms/pull/111 and https://github.com/ezsystems/repository-forms/pull/132
Preface:
And then...
> EZP-27492 Content draft edit

- tests/RepositoryForms/Validator/Constraints/UniqueLanguageCodeValidatorTest.php
For more details please check #156
> Backport of UniqueLanguageCodeValidatorTest

- bundle/Resources/config/services.yml
- lib/FieldType/Mapper/ISBNFormMapper.php
> JIRA: https://jira.ez.no/browse/EZP-27661
This PR provides basic editing support for:
* `ezisbn` [EZP-27661: Implement editing support for ISBN FieldType](https://jira.ez.no/browse/EZP-27661)
> EZP-27661: Implement editing support for ISBN FieldType

- bundle/Resources/config/services.yml
- lib/FieldType/Mapper/MapLocationFormMapper.php
- lib/Form/Type/FieldValue/MapLocationType.php
> JIRA: https://jira.ez.no/browse/EZP-27639
* `ezgmaplocation` [EZP-27639: Implement editing support for MapLocation FieldType](https://jira.ez.no/browse/EZP-27639)
Please note it isn't prepared for Content translation yet. It also requires JS enrichment done in Hybrid UI.
> EZP-27639: Implement editing support for MapLocation FieldType

- bundle/Resources/config/services.yml
- lib/FieldType/DataTransformer/KeywordValueTransformer.php
- lib/FieldType/Mapper/KeywordFormMapper.php
> JIRA: https://jira.ez.no/browse/EZP-27638
* `ezkeyword` [EZP-27638: Implement editing support for Keyword FieldType](https://jira.ez.no/browse/EZP-27638) 
Please note it isn't prepared for Content translation yet.
> EZP-27638: Implement editing support for Keyword

- bundle/Resources/config/services.yml
- doc/bc/changes-1.10.md
- lib/FieldType/DataTransformer/CountryValueTransformer.php
- lib/FieldType/DataTransformer/MultipleCountryValueTransformer.php
- lib/FieldType/DataTransformer/SingleCountryValueTransformer.php
- lib/FieldType/Mapper/CountryFormMapper.php
> JIRA: https://jira.ez.no/browse/EZP-27633
* `ezcountry` [EZP-27633: Implement editing support for Country FieldType](https://jira.ez.no/browse/EZP-27633) 
Please note it isn't prepared for Content translation yet.
> EZP-27633: Implement editing support for Country FieldType

- lib/FieldType/DataTransformer/TimeValueTransformer.php
- lib/Form/Type/FieldType/TimeFieldType.php
> JIRA: https://jira.ez.no/browse/EZP-28204
This PR changes `eztime` form type data format to a timestamp which is easier to be handled by a JS datepicker components.
> EZP-28204: Change view data format to timestamp for TimeFieldType

- lib/FieldType/DataTransformer/DateTimeValueTransformer.php
- lib/Form/Type/FieldType/DateTimeFieldType.php
> JIRA: https://jira.ez.no/browse/EZP-28218
This PR changes `ezdatetime` form type data format to a timestamp which is easier to be handled by a JS datepicker components.
> EZP-28218: Change view data format to timestamp for DateTimeFieldType

- bundle/Resources/config/fieldtypes.yml
- bundle/Resources/translations/ezrepoforms_fieldtype.en.xlf
- lib/FieldType/DataTransformer/AbstractBinaryBaseTransformer.php
- lib/FieldType/DataTransformer/BinaryFileValueTransformer.php
- lib/FieldType/DataTransformer/ImageValueTransformer.php
- lib/FieldType/DataTransformer/MediaValueTransformer.php
- lib/FieldType/Mapper/BinaryFileFormMapper.php
- lib/FieldType/Mapper/ImageFormMapper.php
- lib/FieldType/Mapper/MediaFormMapper.php
- lib/Form/Type/FieldType/BinaryBaseFieldType.php
- lib/Form/Type/FieldType/BinaryFileFieldType.php
- lib/Form/Type/FieldType/ImageFieldType.php
- lib/Form/Type/FieldType/MediaFieldType.php
> JIRA: https://jira.ez.no/browse/EZP-28242
> Original story this PR was created for: https://jira.ez.no/browse/EZP-26700
This PR provides basic editing support for:
* `ezbinaryfile` [EZP-27630: Implement editing support for BinaryFile FieldType](https://jira.ez.no/browse/EZP-27630) 
* `ezimage` [EZP-27629: Implement editing support for Image FieldType](https://jira.ez.no/browse/EZP-27629) 
* `ezmedia` [EZP-27640: Implement editing support for Media FieldType](https://jira.ez.no/browse/EZP-27640)
> EZP-28242: Implement editing support for ezbinary, ezmedia and ezimage fieldtypes

- bundle/Controller/ContentEditController.php
> JIRA: https://jira.ez.no/browse/EZP-28268
This PR provides additional data to the content editing views:
- content draft edit: content and contentType
- draft create: contentInfo and contentType
> EZP-28268: Expose content, content type and location related variables to content edit view

- lib/Form/Type/FieldType/AuthorFieldType.php
> JIRA: https://jira.ez.no/browse/EZP-28371
This PR fixes default behavior of Author fieldtype. It filters out all empty rows from the model value which prevents from creating empty list items in content view.
Also it adds an empty row if the value object has no authors added which helps in case theme adds add/remove buttons in relation to the row.
> EZP-28371: Author fieldtype is not filtering out empty rows

- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/views/ContentType/field_types.html.twig
- lib/FieldType/Mapper/RelationListFormMapper.php
- lib/Form/Type/FieldType/RelationFieldType.php
- lib/Form/Type/FieldType/RelationListFieldType.php
> JIRA: https://jira.ez.no/browse/EZP-28411
Reflects change from https://github.com/ezsystems/ezpublish-kernel/pull/2178
> EZP-28411: Provide support for selection limit setting in ezobjectrelationlist fieldtype

- bundle/Resources/views/ContentType/field_types.html.twig
https://jira.ez.no/browse/EZP-28497
> EZP-28497: Corrected relation default location selection button CSS class name

- lib/Limitation/Mapper/SubtreeLimitationMapper.php
- lib/Limitation/Mapper/UDWBasedMapper.php
- tests/RepositoryForms/Limitation/Mapper/SubtreeLimitationMapperTest.php
- tests/RepositoryForms/Limitation/Mapper/UDWBasedMapperTest.php
https://jira.ez.no/browse/EZP-28492
> EZP-28492: Fix limitation path order

- .travis.yml
- composer.json
> Require PHP 7.1 and add testing for PHP 7.2

- tests/RepositoryForms/FieldType/Mapper/UserAccountFieldValueFormMapperTest.php
> JIRA: https://jira.ez.no/browse/EZP-28532
> EZP-28532: Fix User related tests

- lib/FieldType/Mapper/AuthorFormMapper.php
- lib/FieldType/Mapper/BinaryFileFormMapper.php
- lib/FieldType/Mapper/CheckboxFormMapper.php
- lib/FieldType/Mapper/CountryFormMapper.php
- lib/FieldType/Mapper/DateFormMapper.php
- lib/FieldType/Mapper/DateTimeFormMapper.php
- lib/FieldType/Mapper/FloatFormMapper.php
- lib/FieldType/Mapper/FormTypeBasedFieldValueFormMapper.php
- lib/FieldType/Mapper/ISBNFormMapper.php
- lib/FieldType/Mapper/ImageFormMapper.php
- lib/FieldType/Mapper/IntegerFormMapper.php
- lib/FieldType/Mapper/KeywordFormMapper.php
- lib/FieldType/Mapper/MapLocationFormMapper.php
- lib/FieldType/Mapper/MediaFormMapper.php
- lib/FieldType/Mapper/RelationFormMapper.php
- lib/FieldType/Mapper/RelationListFormMapper.php
- lib/FieldType/Mapper/RichTextFormMapper.php
- lib/FieldType/Mapper/SelectionFormMapper.php
- lib/FieldType/Mapper/TextBlockFormMapper.php
- lib/FieldType/Mapper/TextLineFormMapper.php
- lib/FieldType/Mapper/TimeFormMapper.php
- lib/FieldType/Mapper/UrlFormMapper.php
- lib/FieldType/Mapper/UserAccountFieldValueFormMapper.php
- tests/RepositoryForms/FieldType/Mapper/BaseMapperTest.php
> JIRA: https://jira.ez.no/browse/EZP-28531
> EZP-28531: Force calling FieldDefinition->getName() with mainLanguageCode

- bin/.travis/prepare_behat.sh
- composer.json
- features/Context/ContentEdit.php
- features/Context/FieldTypeFormContext.php
- features/Context/SelectionFieldTypeFormContext.php
- features/Context/UserRegistrationContext.php
> JIRA: https://jira.ez.no/browse/EZP-28224
This PR fixes behat tests and introduces initial configuration for CI to run tests on eZ Platform 2.0.
> EZP-28224: Setup and fix behat tests on repository-forms:2.0

- bundle/Resources/config/services.yml
- bundle/Resources/config/validation.yml
- bundle/Resources/translations/ezrepoforms_url.en.xlf
- bundle/Resources/translations/validators.en.xlf
- lib/Data/URL/URLListData.php
- lib/Data/URL/URLUpdateData.php
- lib/Form/Type/URL/URLEditType.php
- lib/Form/Type/URL/URLListType.php
- lib/Pagination/Pagerfanta/URLSearchAdapter.php
- lib/Pagination/Pagerfanta/URLUsagesAdapter.php
- lib/Validator/Constraints/UniqueURL.php
- lib/Validator/Constraints/UniqueURLValidator.php
- tests/RepositoryForms/Pagination/Pagerfanta/URLSearchAdapterTest.php
- tests/RepositoryForms/Pagination/Pagerfanta/URLUsagesAdapterTest.php
- tests/RepositoryForms/Validator/Constraints/UniqueURLTest.php
- tests/RepositoryForms/Validator/Constraints/UniqueURLValidatorTest.php
> JIRA: https://jira.ez.no/browse/EZP-28495
> **Requires: https://github.com/ezsystems/ezpublish-kernel/pull/2183**
This PR contains common components for the link management UI for v1 and v2, including:
* URL list/update form definition
* DTOs for URL list/update form
* Pagerfanta adapters for listings URLs and content items using URL  
* URL unique constraint
> EZP-28495: As Editor I want UI for external links management

- lib/Form/Processor/ContentFormProcessor.php
> JIRA: https://jira.ez.no/browse/EZP-28571
> EZP-28571: User can't publish content item in another language

- bundle/Controller/ContentEditController.php
- bundle/Controller/UserController.php
- bundle/Controller/UserRegisterController.php
> JIRA: https://jira.ez.no/browse/EZP-28579
> EZP-28579: Pushing Enter in creating mode throws an error

- bundle/Resources/views/Limitation/udw_limitation_value.html.twig
**Jira ticket:** https://jira.ez.no/browse/EZP-28536
> EZP-28536: It's not possible to specify Locations/Subtree of locations for Limitations of Policies

- lib/Form/Processor/ContentFormProcessor.php
JIRA: https://jira.ez.no/browse/EZP-28601
> EZP-28601: Publishing content redirects to parent, not child

- lib/FieldType/Mapper/KeywordFormMapper.php
- lib/FieldType/Mapper/RelationListFormMapper.php
- lib/FieldType/Mapper/TextLineFormMapper.php
> JIRA: https://jira.ez.no/browse/EZP-28649
> EZP-28649: Invalid field type label in content translation

- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- lib/FieldType/Mapper/CheckboxFormMapper.php
> JIRA: https://jira.ez.no/browse/EZP-28651
> EZP-28651: No translation for "Default value" in ezboolean fieldtype definition edit

- lib/Form/Type/FieldType/AuthorFieldType.php
> JIRA: https://jira.ez.no/browse/EZP-28656
Although I fixed this issue in the past, it looks like the fix was insufficient.
> EZP-28656: Author fieldtype is not filtering out empty rows

- .travis.yml
- bin/.travis/prepare_behat.sh
- composer.json
- The PHP 5.6 failure is still the case here even so there seems to be a remaining issue here, for some reason on PHP 5.6 /cc @webhdx
> [Travis] Use Trusty

- lib/Form/Processor/ContentFormProcessor.php
> JIRA: https://jira.ez.no/browse/EZP-28666
> EZP-28666: Content Edit / Cancel action has invalid redirection

- bundle/Controller/UserRegisterController.php
> JIRA: https://jira.ez.no/browse/EZP-28667
> EZP-28667: User registration is not working due to lacking mainLanguageCode option

- bundle/Resources/config/form_types.yml
- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_content.en.xlf
- lib/Data/User/UserAccountFieldData.php
- lib/FieldType/Mapper/UserAccountFieldValueFormMapper.php
- lib/Form/EventSubscriber/UserFieldsSubscriber.php
- lib/Form/Type/FieldType/UserAccountFieldType.php
- lib/Form/Type/SwitcherType.php
- lib/Form/Type/User/BaseUserType.php
> JIRA: https://jira.ez.no/browse/EZP-28664
> EZP-28664: Enabled checkbox should be a part of ezuser fieldtype in Content Edit

- bundle/Resources/views/ContentType/field_types.html.twig
https://jira.ez.no/browse/EZP-28930
> EZP-28930: Labels are one line below checkbox/radiobutton

- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- lib/FieldType/Mapper/ImageFormMapper.php
https://jira.ez.no/browse/EZP-28279
This just changes label for input field.
Main PR: https://github.com/ezsystems/ezpublish-kernel/pull/2280
Frontend: https://github.com/ezsystems/ezplatform-admin-ui/pull/401
> EZP-28279: User cannot set max file size in Image field type

- bundle/Resources/config/form_types.yml
- bundle/Resources/config/services.yml
- lib/ConfigResolver/MaxUploadSize.php
- lib/FieldType/Mapper/BinaryFileFormMapper.php
- lib/FieldType/Mapper/ImageFormMapper.php
- lib/FieldType/Mapper/MediaFormMapper.php
- lib/Form/Type/FieldType/BinaryBaseFieldType.php
https://jira.ez.no/browse/EZP-28551
> EZP-28551: [Media and Binary] You can set maximum file size to less than zero

- features/Context/FieldTypeFormContext.php
Modification of Content Type creation via API for the admin-ui tests.
Related mother-PR - ezsystems/ezplatform-admin-ui#492
> Ezp 29124 - cover basic scenarios of testing fields in content managing

- lib/FieldType/DataTransformer/BinaryFileValueTransformer.php
- lib/Form/Processor/ContentFormProcessor.php
- tests/RepositoryForms/Form/Processor/ContentFormProcessorTest.php
Jira: https://jira.ez.no/browse/EZP-29421
Now when form is sent we set field value only when it was changed.
> EZP-29421: Contents of file field are lost if object is saved before publishing

- bundle/Resources/config/services.yml
- lib/Event/FormActionEvent.php
- lib/Form/Processor/ContentFormProcessor.php
| Tickets       | https://jira.ez.no/browse/EZP-29091
| Tests pass?   | yes :1st_place_medal: 
relevant to : https://github.com/ezsystems/ezplatform-admin-ui/pull/578
> EZP-29091: Publishing Content from the frontend results in error

- .travis.yml
- behat_suites.yml
- features/User/Registration/user_registration.feature
- lib/Behat/Context/ContentEditContext.php
- lib/Behat/Context/ContentTypeContext.php
- lib/Behat/Context/FieldTypeFormContext.php
- lib/Behat/Context/PagelayoutContext.php
- lib/Behat/Context/SelectionFieldTypeFormContext.php
- lib/Behat/Context/UserRegistrationContext.php
Makes tests more generic, for meta-repos other than platform.
JIRA: https://jira.ez.no/browse/EZP-29143
> EZP-29143 run test features on Demo version without changing feature files

- bundle/Resources/translations/ezrepoforms_content.en.xlf
- features/FieldTypeForm/user_fieldtype_edit_form.feature
- lib/Form/Type/FieldType/Author/AuthorEntryType.php
- lib/Form/Type/FieldType/UserAccountFieldType.php
Jira: [https://jira.ez.no/browse/EZP-29684](https://jira.ez.no/browse/EZP-29684)
Related:
- [https://github.com/ezsystems/ezpublish-kernel/pull/2461](uhttps://github.com/ezsystems/ezpublish-kernel/pull/2461l)
- [https://github.com/ezsystems/ezplatform-admin-ui/pull/654](https://github.com/ezsystems/ezplatform-admin-ui/pull/654)
> EZP-29684: Remove the hyphen from the "E-mail" in whole application

- bundle/Controller/UserController.php
- bundle/Resources/config/services.yml
| Tickets       | https://jira.ez.no/browse/EZP-29820
| New feature?  | yes
> EZP-29820: /user/update/{id}/{version}/{language} access limitation

- bundle/Resources/config/fieldtypes.yml
- bundle/Resources/config/services.yml
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- lib/Data/Mapper/UserUpdateMapper.php
- lib/Data/User/UserUpdateData.php
- lib/FieldType/Mapper/UserAccountFieldValueFormMapper.php
- lib/Form/Type/FieldDefinition/User/PasswordConstraintCheckboxType.php
- lib/Validator/Constraints/FieldTypeValidator.php
- lib/Validator/Constraints/Password.php
- lib/Validator/Constraints/PasswordValidator.php
- lib/Validator/Constraints/UserAccountPassword.php
- lib/Validator/Constraints/UserAccountPasswordValidator.php
- lib/Validator/ValidationErrorsProcessor.php
- tests/RepositoryForms/FieldType/Mapper/UserAccountFieldValueFormMapperTest.php
- tests/RepositoryForms/Form/Processor/ContentTypeFormProcessorTest.php
- tests/RepositoryForms/Twig/LimitationValueRenderingExtensionTest.php
- tests/RepositoryForms/Validator/Constraints/PasswordTest.php
- tests/RepositoryForms/Validator/Constraints/PasswordValidatorTest.php
- tests/RepositoryForms/Validator/Constraints/UserAccountPasswordTest.php
- tests/RepositoryForms/Validator/Constraints/UserAccountPasswordValidatorTest.php
- tests/RepositoryFormsBundle/DependencyInjection/Compiler/LimitationValueMapperPassTest.php
| **JIRA issue**     | https://jira.ez.no/browse/EZP-29122
| **Bug/Improvement**| no
| **New feature**    | yes
| **Target version** | `master`
| **BC breaks**      | no
| **Tests pass**     |  yes
:exclamation:  **Depends on https://github.com/ezsystems/ezpublish-kernel/pull/2482** 
**TODO**:
> EZP-29122: As a developer, I want to configure password policies in ezuser

- lib/Event/FormActionEvent.php
- lib/Form/Processor/ContentFormProcessor.php
JIRA: https://jira.ez.no/browse/EZEE-2132
> EZEE-2132: User should be redirected to created Landing Page instead of it's parent

- bundle/Resources/translations/ezplatform_fields_groups.en.xlf
- bundle/Resources/translations/ezrepoforms_content.en.xlf
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/translations/ezrepoforms_fieldtype.en.xlf
- bundle/Resources/translations/ezrepoforms_language.en.xlf
- bundle/Resources/translations/ezrepoforms_role.en.xlf
- bundle/Resources/translations/ezrepoforms_section.en.xlf
- bundle/Resources/translations/ezrepoforms_url.en.xlf
- bundle/Resources/translations/validators.en.xlf
JIRA: - 
This PR updates xliff files.
> Updated translation files

- features/Context/ContentType.php
- features/Context/UserRegistrationContext.php
Implements https://jira.ez.no/browse/EZP-30008
Use `prefix` and `more_entropy` wherever possible.
See also
https://github.com/ezsystems/ezpublish-kernel/pull/2523
https://github.com/ezsystems/BehatBundle/pull/72
> EZP-30008: More unique uniqid()

- lib/FieldType/Mapper/MediaFormMapper.php
| Tickets       | https://jira.ez.no/browse/EZP-29857
Previous:
https://github.com/ezsystems/ezplatform-admin-ui/pull/735
adminUI:
https://github.com/ezsystems/ezplatform-admin-ui/pull/808
> EZP-29857: Unable to upload audio to Media field type

- bundle/Resources/config/form_types.yml
- lib/FieldType/Mapper/RelationFormMapper.php
- lib/FieldType/Mapper/RelationListFormMapper.php
- lib/Form/Type/LocationType.php
> JIRA: https://jira.ez.no/browse/EZP-30172
Solution same as for Image Asset field type. Ref. https://github.com/ezsystems/repository-forms/blob/master/lib/Form/Type/FieldType/ImageAssetFieldType.php#L96-L109
> EZP-30172: Cannot edit Content Type with ezobjectrelation with deleted starting location

- lib/Data/User/UserRegisterData.php
>JIRA: https://jira.ez.no/browse/EZP-29104
Fix BC, same way as we deal with Interfaces in adminUI.
Look also:
https://github.com/ezsystems/ezplatform-user/pull/4
> EZP-29104: Create correct deprecations

- bundle/Resources/views/ContentType/field_types.html.twig
> Jira: https://jira.ez.no/browse/EZP-30362
https://github.com/ezsystems/ezplatform-admin-ui/pull/933
> EZP-30362: Hidden default location in Relation List field type crashes Content Type editing

- lib/Form/DataTransformer/MultilingualSelectionTransformer.php
JIRA: https://jira.ez.no/browse/EZP-30586
> EZP-30586: Adding of Selection FieldType without configured options leads to an 500 error

- lib/Form/Processor/ContentFormProcessor.php
This is part of https://github.com/ezsystems/ezplatform-admin-ui/pull/1005
> EZP-29694: Changed publishing to publish last modified translation

- bundle/Controller/UserController.php
- bundle/Resources/views/Content/content_create_draft.html.twig
- bundle/Resources/views/Content/content_edit.html.twig
- bundle/Resources/views/content_name/content_name.html.twig
- features/User/Registration/user_registration.feature
- lib/Content/View/Builder/ContentCreateViewBuilder.php
- lib/Content/View/Builder/ContentEditViewBuilder.php
- lib/EventListener/ViewTemplatesListener.php
jira: https://jira.ez.no/browse/EZP-30503
related to : https://github.com/ezsystems/ezplatform-admin-ui/pull/986
> EZP-30503: Change names of paramters

- bundle/Resources/views/ContentType/field_definition_row.html.twig
- lib/Twig/FieldEditRenderingExtension.php
- tests/RepositoryForms/Twig/_fixtures/field_edit_rendering_functions/ez_render_fielddefinition_edit.test
related to https://github.com/ezsystems/ezplatform-admin-ui/pull/1008
> EZP-30627: Unified Twig helpers naming

- behat_suites.yml
- lib/Behat/Context/PagelayoutContext.php
- lib/Behat/Context/UserRegistrationContext.php
Description in https://github.com/ezsystems/BehatBundle/pull/87
> EZP-30668: move core tests classes from AdminUI to BehatBundle

- bundle/Resources/config/services.yaml
- lib/Form/Type/ContentType/FieldTypeChoiceType.php
> JIRA: https://jira.ez.no/browse/EZP-30529
Aligns to changes done in https://github.com/ezsystems/ezpublish-kernel/pull/2688
> EZP-30529: Injected Field Types into Repository from DI Container

- bundle/Resources/config/views.yaml
> JIRA: https://jira.ez.no/browse/EZP-30880
> Requires: https://github.com/ezsystems/ezpublish-kernel/pull/2745
> EZP-30880: Aligned Matcher Factories services definitions with Kernel changes

- bundle/Resources/config/ezpublish_default_settings.yaml
- bundle/Resources/config/kernel.yaml
- bundle/Resources/config/role.yaml
> Jira: https://jira.ez.no/browse/EZP-30906
main PR:
https://github.com/ezsystems/ezplatform/pull/453
> EZP-30906: Removed deprecated templating component integration

- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- lib/FieldType/Mapper/UserAccountFieldValueFormMapper.php
> JIRA: https://jira.ez.no/browse/EZP-30797
> **Depends on**: https://github.com/ezsystems/ezpublish-kernel/pull/2742
Part of the https://github.com/ezsystems/ezpublish-kernel/pull/2742
> EZP-30797: As an administrator, I want to configure a password expiration for users

- behat_suites.yml
- lib/Behat/Context/ContentTypeContext.php
- lib/Behat/Context/UserRegistrationContext.php
> Jira: https://jira.ez.no/browse/EZP-30938
> EZP-30938: Removed usage of deprecated setCurrentUser method

- composer.json
- lib/Behat/Context/UserRegistrationContext.php
- lib/Form/EventSubscriber/UserFieldsSubscriber.php
- lib/Form/Processor/User/UserCreateFormProcessor.php
- lib/Form/Processor/User/UserUpdateFormProcessor.php
>Jira: https://jira.ez.no/browse/EZP-30394
Related to changes in 
https://github.com/ezsystems/ezpublish-kernel/pull/2621
> EZP-30394: Re-implement User Field Type

- composer.json
merged in https://github.com/ezsystems/repository-forms/pull/317/commits/b367afdaadb9f0cbe5c66306b9384ccba46fc00d
> Reverted TMP travis config

- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- lib/FieldType/Mapper/UserAccountFieldValueFormMapper.php
> JIRA:  https://jira.ez.no/browse/EZP-30983
> Requires: https://github.com/ezsystems/ezpublish-kernel/pull/2788
See https://github.com/ezsystems/ezpublish-kernel/pull/2788
> EZP-30983: As an Administrator, I want prevent users from reusing old password

- bundle/Resources/translations/ezrepoforms_content.en.xlf
- bundle/Resources/translations/ezrepoforms_content_type.en.xlf
- bundle/Resources/translations/ezrepoforms_fieldtype.en.xlf
- bundle/Resources/translations/ezrepoforms_role.en.xlf
- bundle/Resources/translations/ezrepoforms_user.en.xlf
- bundle/Resources/translations/messages.en.xlf
- bundle/Resources/translations/validators.en.xlf
- lib/Form/Type/FieldType/MediaFieldType.php
- lib/Translation/SortingTranslationExtractor.php
- lib/Validator/Constraints/FieldValueValidatorMessages.php
| Tickets       | https://jira.ez.no/browse/EZP-31020
| Bug fix?      | no
| Tests pass?   | yes/no
https://github.com/ezsystems/ezplatform-admin-ui/pull/1115
> EZP-31020: Revised UI labels and messages

- .travis.yml
- composer.json
- lib/FieldType/DataTransformer/SingleCountryValueTransformer.php
- phpunit.xml.dist
- tests/RepositoryForms/FieldType/DataTransformer/SingleCountryValueTransformerTest.php
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EZP-31542](https://jira.ez.no/browse/EZP-31542)
| **Type**                                   | improvement
| **BC breaks**                          | no
| **Tests pass**                          | yes
| **Doc needed**                       | no
> EZP-31542: Added PHP 7.4 support (eZ Platform 2.5)
